using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

namespace JuegoDef.Env
{
    /// <summary>
    /// Step 7 of the ENV factory: builds a whole district from the spec generated by
    /// Tools/env_district_skeleton.py (Env/Specs/districts/&lt;id&gt;.json): heightfield ground meshes by paving zone,
    /// one facade row per block edge (the street assembler's party-wall/quoin rules, buildings on the terrain with a
    /// stone base where the ground falls away), garden walls, the channelled river with its walls, parapets and bridges,
    /// stairs, and the GC2 player. Builds in chunks (Begin, BuildRows(from, count)..., Finish) so the operator never
    /// holds the Editor in one long call. Menu: JuegoDef &gt; ENV &gt; 7 Build District (CASCO).
    /// </summary>
    public static class EnvDistrict
    {
        public const string DistrictSpecs = EnvKit.Specs + "/districts";
        static JObject spec;
        static string id;
        static Dictionary<string, JObject> units;

        /// <summary>Paving material -> UV tile size (m per texture repeat). The ENV_Pave textures span 4 m.</summary>
        static readonly Dictionary<string, float> PaveTile = new Dictionary<string, float>
        {
            { "ENV_Pave_CantoKit", 1.6f }, { "ENV_Pave_CantoKit_Viejo", 1.5f }, { "ENV_Pave_Canto", 3.4f }, { "ENV_Pave_Canto_Viejo", 3.0f },
            { "ENV_Pave_Losa", 4.4f }, { "ENV_Pave_Losa_Viejo", 4.2f }, { "ENV_Pave_Adoquin", 3.2f }, { "ENV_Pave_Adoquin_Viejo", 3.2f },
            { "ENV_Pave_Plaza", 4.8f }, { "ENV_Pave_Plaza_Viejo", 4.8f }, { "ENV_Ground_Concrete", 3f },
            { "ENV_Ground_Grass", 4f }, { "ENV_Ground_Earth", 6f },
        };

        static Transform Root { get { EnsureSpec(); return GameObject.Find(id)?.transform; } }

        /// <summary>Static state does not survive a domain reload between chunked calls: recover the district id from
        /// the open scene (its root object) and reload the spec and the unit library.</summary>
        static void EnsureSpec()
        {
            if (spec != null && units != null && id != null) return;
            if (id == null)
                id = UnityEngine.SceneManagement.SceneManager.GetActiveScene().GetRootGameObjects()
                        .Select(g => g.name).FirstOrDefault(n => n.StartsWith("ENV01_") && System.IO.File.Exists($"{DistrictSpecs}/{n}.json"));
            if (id == null) throw new System.InvalidOperationException("JD_DISTRICT_NO_STATE: call Begin(id) first");
            spec = JObject.Parse(EnvKit.ReadText($"{DistrictSpecs}/{id}.json"));
            units = JObject.Parse(EnvKit.ReadText(EnvKit.Specs + "/units.json"))["units"].ToDictionary(u => (string)u["id"], u => (JObject)u);
        }
        static string MeshFolder => $"{EnvKit.Derived}/District/{id}";

        [MenuItem("JuegoDef/ENV/7 Build District (CASCO)")]
        public static void BuildMenu()
        {
            Debug.Log(Begin("ENV01_Casco_District"));
            Debug.Log(BuildRows(0, int.MaxValue));
            Debug.Log(Finish());
        }

        public static string Begin(string districtId)
        {
            id = districtId;
            spec = JObject.Parse(EnvKit.ReadText($"{DistrictSpecs}/{id}.json"));
            EnvKit.ClearCache();
            EnvClearance.ClearCache();
            BuildingAssembler.ReloadGrammar();
            EnvBusiness.Reset();
            units = JObject.Parse(EnvKit.ReadText(EnvKit.Specs + "/units.json"))["units"].ToDictionary(u => (string)u["id"], u => (JObject)u);
            var stage = EnvPreview.NewStage(id, ground: false);
            Object.DestroyImmediate(stage.gameObject);
            var root = new GameObject(id).transform;
            int tris = BuildGround(root);
            PavingOverlays(root);
            return $"JD_DISTRICT_BEGIN {id} ground tris={tris} rows={((JArray)spec["rows"]).Count}";
        }

        // ------------------------------------------------------------------ ground

        /// <summary>Streets of the spec as polylines (x, z) with width, role and id, for "which street is this on".</summary>
        static List<(string id, string role, float w, List<Vector2> pts)> StreetLines() =>
            ((JArray)spec["streets"]).Cast<JObject>().Select(st => ((string)st["id"], (string)st["role"], (float)st["width"],
                ((JArray)st["pts"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList())).ToList();

        static float Hash01(float x, float y, float salt)
        {
            float h = Mathf.Sin(x * 12.9898f + y * 78.233f + salt * 37.719f) * 43758.5453f;
            return h - Mathf.Floor(h);
        }

        /// <summary>Paving by reason, not one sett everywhere (owner audit points 13/14): the main spine keeps river
        /// cobbles with its central strip of flags (the old cart track, only there), secondary streets a finer
        /// canto, lanes an older darker canto, the bridge approaches granite setts, the plaza big square slabs;
        /// and repaired patches — setts or concrete — where the street was opened for pipes. Relabels the spec's
        /// zone triangles; the spec geometry (and so the walkable surface) is unchanged.</summary>
        static string PaveOf(string zone, Vector2 c, List<(string id, string role, float w, List<Vector2> pts)> streets)
        {
            // huertas and back yards as a patchwork of tilled plots and meadow, not one brown mat (owner point 37)
            if (zone == "yard" || zone == "huerta")
            {
                float px = Mathf.Floor(c.x / 7.5f), pz = Mathf.Floor(c.y / 5.5f);
                return Hash01(px, pz, zone == "huerta" ? 51 : 52) < (zone == "huerta" ? 0.45f : 0.22f) ? "ENV_Ground_Earth" : "ENV_Ground_Grass";
            }
            if (zone == "outer") return "ENV_Ground_Grass";
            var near = streets.OrderBy(st => (Nearest(st.pts, c) - c).sqrMagnitude).First();
            string role = zone == "plaza" ? "plaza" : near.role;
            // repairs: patches on a jittered 3 m grid, likelier on the busy streets
            float gx = Mathf.Floor(c.x / 3.1f), gz = Mathf.Floor(c.y / 2.7f);
            float rep = Hash01(gx, gz, 1);
            if (zone != "strip" && role != "plaza" && rep < (role == "main" ? 0.05f : 0.035f))
                return Hash01(gx, gz, 2) < 0.6f ? "ENV_Pave_Adoquin_Viejo" : "ENV_Ground_Concrete";
            switch (role)
            {
                case "main":
                    return zone == "strip" ? "ENV_Pave_Losa_Viejo" : "ENV_Pave_CantoKit";
                case "plaza":
                    // big irregular flags on the open floor, cobbles along the house fronts
                    return PlazaRim(c) ? "ENV_Pave_CantoKit" : "ENV_Pave_Losa";
                case "bridge":
                case "footbridge":
                    return "ENV_Pave_Adoquin";
                case "secondary":
                    return near.id.StartsWith("Ribera") || near.id.StartsWith("Capitan") ? "ENV_Pave_Canto_Viejo" : "ENV_Pave_Canto";
                default:
                    return "ENV_Pave_CantoKit_Viejo";   // lanes, stairs heads, rims
            }
        }

        static List<List<Vector2>> plazaPolys;
        static bool PlazaRim(Vector2 c)
        {
            plazaPolys ??= ((JArray)spec["plazas"]).Cast<JObject>().Select(pz => ((JArray)pz["poly"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList()).ToList();
            var poly = plazaPolys.FirstOrDefault(pl => Inside(pl, c));
            return poly == null || EdgeDistance(poly, c) < 2.6f;
        }

        static int BuildGround(Transform root)
        {
            plazaPolys = null;
            EnvKit.EnsureFolder(MeshFolder);
            var g = EnvKit.Group(root, "Ground");
            var streets = StreetLines();
            // gather every zone triangle under its paving material
            var byMat = new Dictionary<string, (List<Vector3> v, List<int> t)>();
            foreach (var kv in (JObject)spec["ground"])
            {
                var v = (JArray)kv.Value["v"];
                var t = ((JArray)kv.Value["t"]).Select(x => (int)x).ToArray();
                var verts = v.Select(q => new Vector3((float)q[0], (float)q[1], (float)q[2])).ToArray();
                for (int k = 0; k < t.Length; k += 3)
                {
                    var a = verts[t[k]]; var b = verts[t[k + 1]]; var c = verts[t[k + 2]];
                    var cen = new Vector2((a.x + b.x + c.x) / 3f, (a.z + b.z + c.z) / 3f);
                    var mat = PaveOf(kv.Key, cen, streets);
                    if (!byMat.TryGetValue(mat, out var acc)) byMat[mat] = acc = (new List<Vector3>(), new List<int>());
                    if (Vector3.Cross(b - a, c - a).y < 0) (b, c) = (c, b);   // front faces up (Unity: clockwise from above)
                    int i0 = acc.v.Count;
                    acc.v.AddRange(new[] { a, b, c });
                    acc.t.AddRange(new[] { i0, i0 + 1, i0 + 2 });
                }
            }
            int total = 0;
            foreach (var kv in byMat)
            {
                float tile = PaveTile.TryGetValue(kv.Key, out var tl) ? tl : 2f;
                var verts = kv.Value.v.ToArray();
                var uvs = verts.Select(p => new Vector2(p.x / tile, p.z / tile)).ToArray();
                MeshObject("Ground_" + kv.Key.Replace("ENV_", ""), g, verts, uvs, kv.Value.t.ToArray(), EnvKit.Mat(kv.Key), collider: true);
                total += kv.Value.t.Count / 3;
            }
            return total;
        }

        /// <summary>Paving overlays laid 8 mm over the walkable ground (visual only, no collider): the drainage
        /// channel of setts down the middle of the lanes, and a band of flags along the facades of the main spine and
        /// some secondary streets — the stone meets the house on a flag, not on loose cobbles (owner point 15).</summary>
        static void PavingOverlays(Transform root)
        {
            var g = EnvKit.Group(root, "PavingOverlays");
            Physics.SyncTransforms();
            var lanes = new List<(List<Vector3> l, List<Vector3> r)>();
            foreach (var st in ((JArray)spec["streets"]).Cast<JObject>())
            {
                string role = (string)st["role"];
                if (role != "lane") continue;
                var pts = ((JArray)st["pts"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList();
                lanes.Add(Ribbon(pts, 0.2f, -0.2f));
            }
            OverlayMesh(g, "Overlay_Canalillo", lanes, "ENV_Pave_Adoquin_Viejo", 0.9f);
            var bands = new List<(List<Vector3> l, List<Vector3> r)>();
            foreach (JObject row in (JArray)spec["rows"])
            {
                string role = (string)row["role"];
                if (role != "main" && !(role == "secondary" && Hash01(((string)row["id"]).GetHashCode() % 997, 3, 5) < 0.55f)) continue;
                var o = new Vector2((float)row["origin"][0], (float)row["origin"][1]);
                var d = new Vector2((float)row["dir"][0], (float)row["dir"][1]);
                // the row frame's +z (street side), from the same rotation BuildRows gives the frame
                var fz = Quaternion.Euler(0, Mathf.Atan2(-d.y, d.x) * Mathf.Rad2Deg, 0) * Vector3.forward;
                var n = new Vector2(fz.x, fz.z);
                foreach (JObject p in (JArray)row["plots"])
                {
                    if ((bool?)p["wall"] == true) continue;
                    float x0 = (float)p["x0"], w = (float)p["w"], sb = (float?)p["setback"] ?? 0f;
                    var a = o + d * (x0 + 0.05f) - n * sb;
                    var b = o + d * (x0 + w - 0.05f) - n * sb;
                    var line = new List<Vector2> { a, b };
                    bands.Add(Ribbon(line, 0.0f, 0.75f, n));
                }
            }
            OverlayMesh(g, "Overlay_Losas_Fachada", bands, "ENV_Pave_Losa", 2.2f);
        }

        /// <summary>Ribbon along a plan polyline between two lateral offsets (left of travel positive), heights from
        /// the district colliders, sampled every metre.</summary>
        static (List<Vector3> l, List<Vector3> r) Ribbon(List<Vector2> pts, float offL, float offR, Vector2? normal = null)
        {
            var L = new List<Vector3>();
            var R = new List<Vector3>();
            for (int i = 0; i + 1 < pts.Count; i++)
            {
                var a = pts[i]; var b = pts[i + 1];
                float len = (b - a).magnitude;
                if (len < 0.05f) continue;
                var dir = (b - a) / len;
                var nrm = normal ?? new Vector2(-dir.y, dir.x);
                int n = Mathf.Max(1, Mathf.CeilToInt(len));
                for (int k = (i == 0 ? 0 : 1); k <= n; k++)
                {
                    var c = a + dir * (len * k / n);
                    var pl = c + nrm * offL; var pr = c + nrm * offR;
                    L.Add(new Vector3(pl.x, GroundY(pl.x, pl.y, float.NaN) + 0.008f, pl.y));
                    R.Add(new Vector3(pr.x, GroundY(pr.x, pr.y, float.NaN) + 0.008f, pr.y));
                }
            }
            return (L, R);
        }

        static void OverlayMesh(Transform g, string name, List<(List<Vector3> l, List<Vector3> r)> ribbons, string mat, float tile)
        {
            var v = new List<Vector3>(); var t = new List<int>(); var uv = new List<Vector2>();
            foreach (var (L, R) in ribbons)
                for (int k = 0; k + 1 < L.Count; k++)
                {
                    // skip samples that found no ground (off the district colliders) or that jump (walls, stairs)
                    var q = new[] { L[k], L[k + 1], R[k + 1], R[k] };
                    if (q.Any(p => float.IsNaN(p.y))) continue;
                    if (Mathf.Max(q.Max(p => p.y) - q.Min(p => p.y), 0) > 0.45f) continue;
                    int i0 = v.Count;
                    v.AddRange(q);
                    uv.AddRange(q.Select(p => new Vector2(p.x / tile, p.z / tile)));
                    var nrm = Vector3.Cross(q[1] - q[0], q[2] - q[0]);
                    t.AddRange(nrm.y >= 0 ? new[] { i0, i0 + 2, i0 + 1, i0, i0 + 3, i0 + 2 } : new[] { i0, i0 + 1, i0 + 2, i0, i0 + 2, i0 + 3 });
                }
            if (v.Count == 0) return;
            var go = MeshObject(name, g, v.ToArray(), uv.ToArray(), t.ToArray(), EnvKit.Mat(mat), collider: false);
            go.GetComponent<MeshRenderer>().shadowCastingMode = ShadowCastingMode.Off;
        }

        static GameObject MeshObject(string name, Transform parent, Vector3[] verts, Vector2[] uvs, int[] tris, Material mat, bool collider)
        {
            var mesh = new Mesh { name = $"{id}_{name}", indexFormat = verts.Length > 65000 ? IndexFormat.UInt32 : IndexFormat.UInt16 };
            mesh.SetVertices(verts);
            mesh.SetUVs(0, uvs);
            mesh.SetTriangles(tris, 0);
            mesh.RecalculateNormals();
            mesh.RecalculateTangents();
            mesh.RecalculateBounds();
            var path = $"{MeshFolder}/{name}.asset";
            AssetDatabase.DeleteAsset(path);
            AssetDatabase.CreateAsset(mesh, path);
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            go.AddComponent<MeshFilter>().sharedMesh = mesh;
            go.AddComponent<MeshRenderer>().sharedMaterial = mat;
            if (collider) go.AddComponent<MeshCollider>().sharedMesh = mesh;
            GameObjectUtility.SetStaticEditorFlags(go, EnvKit.StaticFlags);
            return go;
        }

        // ------------------------------------------------------------------ rows

        public static string BuildRows(int from, int count)
        {
            EnsureSpec();
            var root = Root;
            var rows = (JArray)spec["rows"];
            var rg = EnvKit.Group(root, "Rows");
            int buildings = 0, walls = 0, end = (int)Mathf.Min(rows.Count, (long)from + count);
            var sw = System.Diagnostics.Stopwatch.StartNew();
            for (int r = from; r < end; r++)
            {
                var row = (JObject)rows[r];
                var frame = new GameObject((string)row["id"]).transform;
                frame.SetParent(rg, false);
                frame.localPosition = new Vector3((float)row["origin"][0], 0, (float)row["origin"][1]);
                frame.localRotation = Quaternion.Euler(0, Mathf.Atan2(-(float)row["dir"][1], (float)row["dir"][0]) * Mathf.Rad2Deg, 0);
                var placed = new List<EnvStreet.Placed>();
                var plots = ((JArray)row["plots"]).Cast<JObject>().ToList();
                string prevHue = null;
                for (int k = 0; k < plots.Count; k++)
                {
                    var p = plots[k];
                    if ((bool?)p["wall"] == true) { placed.Add(null); continue; }
                    var bs = SpecOf(p, $"{row["id"]}_{k}");
                    if (p["unit"] == null || (string)p["landmark"] == "Torre") EnvCharacter.Apply(bs, p, row, ref prevHue);
                    float w = (float)p["w"];
                    placed.Add(new EnvStreet.Placed { spec = bs, x0 = (float)p["x0"], width = w, scale = w / (bs.bays * 2f), setback = (float?)p["setback"] ?? 0f, y = (float)p["y"] });
                }
                EnvStreet.ResolveNeighbours(placed, (JObject)row["ends"]);
                foreach (var p in placed.Where(p => p != null))
                {
                    var go = BuildingAssembler.Build(p.spec, frame);
                    go.transform.localPosition = new Vector3(p.x0, p.y, -p.setback);
                    if (Mathf.Abs(p.scale - 1f) > 0.001f) go.transform.localScale = new Vector3(p.scale, 1, 1);
                    buildings++;
                }
                foreach (var p in plots.Where(p => (bool?)p["wall"] == true))
                {
                    GardenWall(frame, p);
                    walls++;
                }
            }
            return $"JD_DISTRICT_ROWS {from}..{end - 1} buildings={buildings} walls={walls} ms={sw.ElapsedMilliseconds}";
        }

        static readonly Dictionary<int, string[]> CasonaRows = new Dictionary<int, string[]>
        {
            // few openings: arched portal with the shield above it, windows on the principal floor, the top floor opening
            // onto the solana through its one door
            { 4, new[] { "WPAP", "PWPW", "wPNw" } },
            { 5, new[] { "PWAWP", "WPPPW", "PwNwP" } },
        };

        static BuildingSpec SpecOf(JObject p, string name)
        {
            BuildingSpec bs;
            if (p["unit"] != null)
            {
                bs = ((JObject)units[(string)p["unit"]]["building"]).ToObject<BuildingSpec>();
                bs.floors = (int?)p["floors"] ?? bs.floors;
            }
            else
                bs = new BuildingSpec
                {
                    type = (string)p["type"], bays = (int)p["bays"], depth = (int)p["depth"], floors = (int)p["floors"],
                    seed = (int?)p["seed"] ?? 1, palette = (string)p["palette"], ground = (string)p["ground"] ?? "", upper = (string)p["upper"] ?? "plaster",
                };
            bs.id = name;
            if (p["era"] != null) bs.era = (string)p["era"];
            if (p["rows"] is JArray rows) bs.rows = rows.Select(x => (string)x).ToArray();
            if (p["awning"] != null) bs.awning = (string)p["awning"];
            bs.solana = (bool?)p["solana"] == true;
            bs.surrounds = (bool?)p["surrounds"] == true;
            bs.escudo = (bool?)p["escudo"] == true;
            if ((bool?)p["casona"] == true)
            {
                bs.era = "old";
                bs.ground = "stone";
                bs.solana = bs.floors >= 3;
                bs.escudo = true;
                bs.surrounds = true;
                if (CasonaRows.TryGetValue(bs.bays, out var cr)) bs.rows = cr.Take(bs.floors).ToArray();
            }
            bs.basement = (float?)p["basement"] ?? 0f;
            // shop life (owner photos): striped awnings and wrought-iron hanging signs on a good share of the shops
            var lrng = new System.Random(bs.seed * 13 + 7);
            if (bs.type == "mixed_commercial" && string.IsNullOrEmpty(bs.awning) && lrng.NextDouble() < 0.55)
                bs.awning = new[] { "ENV_Canvas_Green", "ENV_Canvas_Red", "ENV_Canvas_Cream" }[lrng.Next(3)];
            if ((bs.type == "mixed_commercial" || bs.type == "lodging") && lrng.NextDouble() < 0.5) bs.sign = "bracket";
            return bs;
        }

        /// <summary>Rubble garden wall (huertas) along a row stretch, stepping with the ground every 2 m; a timber gate
        /// where the spec asks for one. "tall" walls close a street wall where a block was too thin for a building.</summary>
        static void GardenWall(Transform frame, JObject p)
        {
            var g = EnvKit.Group(frame, "Walls");
            float x0 = (float)p["x0"], w = (float)p["w"];
            var ys = ((JArray)p["ys"])?.Select(v => (float)v).ToArray() ?? new[] { 0f };
            bool tall = (bool?)p["tall"] == true;
            float h = tall ? 4.6f : 2.2f;
            float gate = (float?)p["gate"] ?? -10f;
            int n = Mathf.Max(1, Mathf.CeilToInt(w / 2f - 0.01f));
            float seg = w / n;
            // each wall its own dry masonry (lajas, rubble, river stones) with damp at the foot; long runs broken by
            // ivy over the coping, a damp or algae patch, weeds on top (owner point 21: "paredes demasiado largas")
            var key = new Vector2(frame.position.x + x0, frame.position.z + x0 * 0.7f);
            float hh = Hash01(key.x, key.y, 41);
            string bond = hh < 0.45f ? "Laja" : hh < 0.8f ? "Mamposteria" : "Canto";
            string tone = new[] { "Caliza", "Gris", "Arenisca", "Oscura" }[(int)(Hash01(key.x, key.y, 42) * 4) % 4];
            var map = new Dictionary<string, string> { { "MI_UnevenBrick", $"ENV_Mason_{bond}_{tone}_G" }, { "MI_RockTrim", "ENV_Dressed_Gris" } };
            for (int k = 0; k < n; k++)
            {
                float xc = x0 + seg * (k + 0.5f);
                float y = ys[Mathf.Clamp(Mathf.RoundToInt((xc - x0) / 2f), 0, ys.Length - 1)];
                if (gate > 0 && Mathf.Abs(xc - (x0 + gate)) < seg / 2f)
                {
                    // plank gate into the huerta (the kit timber fence is a banned alpine cue)
                    EnvKit.Place("ENV_Gate_Timber", g, new Vector3(xc, y, -0.05f), 0, new Vector3(seg / 1.6f, 0.8f, 1));
                    continue;
                }
                EnvKit.Remap(EnvKit.Place("ENV_Retaining_Wall_2x2", g, new Vector3(xc, y + h, -0.1f), 0, new Vector3(seg / 2f, (h + 0.6f) / 2f, 0.6f)), map);
                float r = Hash01(key.x + k * 2.1f, key.y, 43);
                if (r < 0.16f)
                    EnvKit.Place("Prop_Vine" + (1 + (int)(r * 100) % 3), g, new Vector3(xc, y + h - 0.35f, 0.02f), 0);
                else if (r < 0.3f)
                {
                    var st = EnvKit.Place("ENV_Stain_Quad", g, new Vector3(xc, y, -0.192f), 0, new Vector3(seg * 0.9f, 0.7f + h * 0.25f, 1));
                    EnvKit.Remap(st, new Dictionary<string, string> { { "ENV_Stain_Downpipe", r < 0.22f ? "ENV_Stain_Algae" : "ENV_Stain_Damp" } });
                }
                else if (r < 0.38f)
                    EnvKit.Place("ENV_Weeds_Grass", g, new Vector3(xc, y + h, -0.3f), r * 900f, Vector3.one * 0.55f);
            }
        }

        // ------------------------------------------------------------------ river, bridges, stairs, player

        public static string Finish()
        {
            EnsureSpec();
            var root = Root;
            var river = (JObject)spec["river"];
            var rv = EnvKit.Group(root, "River");
            float water = (float)river["water"];
            // water surface over the channel polygon (fan triangulation of a simple polygon is not safe: ear clipping)
            var ch = ((JArray)river["channel"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
            if (ch.Count > 3 && (ch[0] - ch[ch.Count - 1]).sqrMagnitude < 1e-6f) ch.RemoveAt(ch.Count - 1);
            var tri = EarClip(ch);
            var wv = ch.Select(c => new Vector3(c.x, water, c.y)).ToArray();
            for (int k = 0; k < tri.Length; k += 3)
                if (Vector3.Cross(wv[tri[k + 1]] - wv[tri[k]], wv[tri[k + 2]] - wv[tri[k]]).y < 0) (tri[k + 1], tri[k + 2]) = (tri[k + 2], tri[k + 1]);
            var waterGo = MeshObject("River_Water", rv, wv, ch.Select(c => c / 4f).ToArray(), tri, EnvKit.Mat("ENV_River_Water"), collider: false);
            waterGo.GetComponent<MeshRenderer>().shadowCastingMode = ShadowCastingMode.Off;
            // the bed: river cobbles under a shallow casco river, so the water has a depth to read (shallows, foam)
            var bed = ch.Select(c => new Vector3(c.x, water - RiverDepth, c.y)).ToArray();
            MeshObject("River_Bed", rv, bed, ch.Select(c => c / 3f).ToArray(), (int[])tri.Clone(), EnvKit.Mat("ENV_Riverbed"), collider: false);
            var centre = ((JArray)river["pts"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
            RiverRocks(rv, ch, centre, water, (float)river["width"]);
            int wallPieces = 0;
            foreach (JArray bank in (JArray)river["banks"])
            {
                var pts = bank.Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
                for (int i = 0; i + 1 < pts.Count; i++)
                {
                    var a = pts[i];
                    var b = pts[i + 1];
                    float len = Vector2.Distance(new Vector2(a.x, a.z), new Vector2(b.x, b.z));
                    if (len < 0.3f) continue;
                    int n = Mathf.Max(1, Mathf.RoundToInt(len / 4f));
                    var d = new Vector2(b.x - a.x, b.z - a.z) / len;
                    var mid = new Vector2((a.x + b.x) / 2, (a.z + b.z) / 2);
                    var toWater = Nearest(centre, mid) - mid;
                    var nrm = new Vector2(-d.y, d.x);
                    if (Vector2.Dot(nrm, toWater) < 0) nrm = -nrm;
                    float yaw = Mathf.Atan2(nrm.x, nrm.y) * Mathf.Rad2Deg;  // piece +z faces the water
                    for (int k = 0; k < n; k++)
                    {
                        float t = (k + 0.5f) / n;
                        var at = Vector3.Lerp(a, b, t);
                        var go = EnvKit.Place("ENV_Quay_Wall_4m", rv, new Vector3(at.x, at.y, at.z), yaw, new Vector3(len / n / 4f + 0.02f, (at.y - water + 0.6f) / 3.2f, 1));
                        // an old channel exposed to constant rain (owner points 22-23): the masonry changes by stretch, the
                        // water line greens it, drains and plants live on it
                        float stretch = Mathf.Floor((at.x + at.z * 1.3f) / 22f);
                        float h = Hash01(stretch, 7, 3);
                        string kind = h < 0.45f ? "Canto" : h < 0.85f ? "Mamposteria" : "Silleria";
                        EnvKit.Remap(go, new Dictionary<string, string> { { "MI_UnevenBrick", "ENV_RiverWall_" + kind }, { "MI_RockTrim", "ENV_Dressed_Gris" } });
                        RiverWallLife(rv, at, yaw, water, len / n, Hash01(at.x, at.z, 11));
                        wallPieces++;
                    }
                }
            }
            foreach (JArray p in (JArray)river["parapets"])
            {
                var a = new Vector2((float)p[0][0], (float)p[0][1]);
                var b = new Vector2((float)p[1][0], (float)p[1][1]);
                var d = b - a;
                var mid = (a + b) / 2;
                EnvKit.Place("ENV_Parapet_Rail_2m", rv, new Vector3(mid.x, (float)p[2], mid.y), Mathf.Atan2(d.y, d.x) * -Mathf.Rad2Deg, new Vector3(d.magnitude / 2f, 1, 1));
            }
            foreach (JObject br in (JArray)spec["bridges"]) Bridge(rv, br, water);
            // stone arches under the decks, spanning the channel at each crossing: dressed voussoirs, the barrel in the
            // weathered river masonry, ivy hanging from the spandrel
            foreach (JObject a in (JArray)spec["bridgeArches"] ?? new JArray())
            {
                var mid = new Vector3((float)a["mid"][0], (float)a["y"], (float)a["mid"][1]);
                float yaw = Mathf.Atan2(-(float)a["dir"][1], (float)a["dir"][0]) * Mathf.Rad2Deg;
                var arch = EnvKit.Place("ENV_Bridge_Arch", EnvKit.Group(rv, (string)a["id"]), mid, yaw, new Vector3(((float)a["span"] + 0.6f) / 10f, 1f, (float)a["width"]));
                EnvKit.Remap(arch, new Dictionary<string, string> { { "MI_UnevenBrick", "ENV_RiverWall_Silleria" }, { "ENV_Stone_Sandstone", "ENV_Dressed_Arenisca" } });
                var dir = new Vector3((float)a["dir"][0], 0, (float)a["dir"][1]);
                var side = new Vector3(-dir.z, 0, dir.x);
                foreach (var sgn in new[] { 1f, -1f })
                    for (int k = -1; k <= 1; k += 2)
                    {
                        var p = mid + dir * k * (float)a["span"] * 0.28f + side * sgn * ((float)a["width"] / 2f + 0.05f);
                        EnvKit.Place("Prop_Vine" + (2 + (k + 1) / 2), rv, new Vector3(p.x, mid.y - 0.3f, p.z), Mathf.Atan2(side.x * sgn, side.z * sgn) * Mathf.Rad2Deg);
                    }
            }
            foreach (JObject r in (JArray)spec["riverStairs"] ?? new JArray())
            {
                var at = new Vector3((float)r["at"][0], (float)r["y"], (float)r["at"][1]);
                var stairs = EnvKit.Place("ENV_River_Stairs", rv, at, Mathf.Atan2(-(float)r["u"][1], (float)r["u"][0]) * Mathf.Rad2Deg);
                EnvKit.Remap(stairs, new Dictionary<string, string> { { "MI_UnevenBrick", "ENV_RiverWall_Mamposteria" } });
            }
            var dress = EnvKit.Group(root, "Dressing");
            foreach (JObject f in (JArray)spec["fountains"] ?? new JArray())
                EnvKit.Place("ENV_Fountain_Trough", dress, new Vector3((float)f["at"][0], (float)f["y"], (float)f["at"][1]),
                             Mathf.Atan2((float)f["face"][0], (float)f["face"][1]) * Mathf.Rad2Deg);
            foreach (JObject gi in (JArray)spec["garden"] ?? new JArray())
            {
                bool tree = (string)gi["item"] == "tree";
                // fruit trees, and low solid shrubs (the kit bush reads as red cards at a distance)
                EnvKit.Place(tree ? "ENV_Tree_Plaza" : "ENV_Hill_Tree", dress, new Vector3((float)gi["at"][0], (float)gi["y"], (float)gi["at"][1]), (float)gi["rot"],
                             Vector3.one * (tree ? (float)gi["scale"] : 0.28f * (float)gi["scale"]));
            }
            Backdrop(root, water);
            var st = EnvKit.Group(root, "Stairs");
            foreach (JObject s in (JArray)spec["stairs"]) Stairs(st, s);
            Physics.SyncTransforms();
            var pl = EnvKit.Group(root, "Plazas");
            int seed = 1;
            foreach (JObject pz in (JArray)spec["plazas"])
                DressPlaza(pl, pz, seed++);
            StreetFurniture(root);

            // player at the river plaza
            var plaza = ((JArray)spec["plazas"]).Cast<JObject>().FirstOrDefault(pz => (string)pz["id"] == "Plaza_Rio");
            var spawn = new Vector3(100, 1, 100);
            if (plaza != null)
            {
                var poly = ((JArray)plaza["poly"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
                var c0 = poly.Aggregate(Vector2.zero, (acc, q) => acc + q) / poly.Count;
                spawn = new Vector3(c0.x, ((float?)plaza["y"] ?? 0f) + 0.2f, c0.y);
            }
            // route probe (disabled; enable for a Play Mode walk): the authored tour of the district
            if (spec["route"] is JArray route && route.Count > 1)
            {
                var probe = new GameObject("RouteProbe");
                probe.transform.SetParent(root, false);
                probe.SetActive(false);
                probe.AddComponent<JuegoDef.Dev.JDRouteProbe>().waypoints = route.Select(w => new Vector3((float)w[0], (float)w[2], (float)w[1])).ToArray();
                spawn = new Vector3((float)route[0][0], (float)route[0][2] + 0.2f, (float)route[0][1]);  // arriving from the east along the spine
            }
            EnvStreet.BringPlayer(new JObject { ["_spawnWorld"] = new JArray(spawn.x, spawn.y, spawn.z) });
            // lighting rig last: it collects the lamps placed above and bakes the reflection probe over the finished town
            var dd = (JArray)spec["district"];
            var db = new Bounds();
            db.SetMinMax(new Vector3((float)dd[0][0], water - 2f, (float)dd[0][1]), new Vector3((float)dd[1][0], water + 30f, (float)dd[1][1]));
            EnvLighting.BuildRig(root, db, water);
            EnvKit.EnsureFolder("Assets/JuegoDef/Scenes/ENV");
            var scenePath = $"Assets/JuegoDef/Scenes/ENV/{id}.unity";
            EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(), scenePath);
            int objects = root.GetComponentsInChildren<Transform>(true).Length;
            return $"JD_DISTRICT_FINISH {id} -> {scenePath} objects={objects} riverWalls={wallPieces}";
        }

        /// <summary>Valley backdrop so the casco is not an island in a void: wooded hills rising around the town, a
        /// lower valley opening to the north where the river runs down to the port, and the sea beyond it (owner:
        /// "al fondo se empieza a intuir el mar"). Cheap: one ring mesh, scattered low-cost trees, one sea plane.</summary>
        static void Backdrop(Transform root, float water)
        {
            var g = EnvKit.Group(root, "Backdrop");
            var d = (JArray)spec["district"];
            var c = new Vector2(((float)d[0][0] + (float)d[1][0]) / 2f, ((float)d[0][1] + (float)d[1][1]) / 2f);
            float x0 = (float)d[0][0], z0 = (float)d[0][1], x1 = (float)d[1][0], z1 = (float)d[1][1];
            float r0 = 0.5f * Mathf.Min(x1 - x0, z1 - z0), r1 = 700f;
            // distance outside the district rectangle: the valley floor meets the district edge, hills rise beyond it
            float Out(float x, float z) => new Vector2(Mathf.Max(0, Mathf.Max(x0 - 14f - x, x - x1 - 14f)), Mathf.Max(0, Mathf.Max(z0 - 14f - z, z - z1 - 14f))).magnitude;
            int na = 96, nr = 14;
            var verts = new List<Vector3>();
            var uvs = new List<Vector2>();
            float H(float ang, float r, float dout)
            {
                // north (+z) is the valley towards the port: low; elsewhere wooded hills 40-90 m
                float fromNorth = Mathf.Abs(Mathf.DeltaAngle(ang * Mathf.Rad2Deg, 90f)) / 180f;          // 0 north .. 1 south
                float hill = 40f + 28f * Mathf.Sin(ang * 3f + 0.7f) + 16f * Mathf.Sin(ang * 7f + 2.1f) + 8f * Mathf.Sin(ang * 13f);
                float open = Mathf.Lerp(0.08f, 1f, Mathf.SmoothStep(0.05f, 0.45f, fromNorth));
                if (dout <= 0.01f) return -1.2f;                        // under the district's own ground
                float rise = Mathf.SmoothStep(0f, 1f, (dout - 8f) / 220f);
                return Mathf.Lerp(-0.3f, hill * open, rise) + (fromNorth < 0.12f ? -Mathf.SmoothStep(0f, 1f, (dout - 60f) / 200f) * 7f : 0f);
            }
            for (int j = 0; j <= nr; j++)
            {
                float r = Mathf.Lerp(r0, r1, Mathf.Pow(j / (float)nr, 1.6f));
                for (int i = 0; i < na; i++)
                {
                    float a = 2 * Mathf.PI * i / na;
                    float px = c.x + Mathf.Cos(a) * r, pz = c.y + Mathf.Sin(a) * r;
                    var p = new Vector3(px, H(a, r, Out(px, pz)), pz);
                    verts.Add(p);
                    uvs.Add(new Vector2(p.x, p.z) / 6f);
                }
            }
            var tris = new List<int>();
            for (int j = 0; j < nr; j++)
                for (int i = 0; i < na; i++)
                {
                    int a0 = j * na + i, a1 = j * na + (i + 1) % na, b0 = a0 + na, b1 = a1 + na;
                    tris.AddRange(new[] { a0, b1, a1, a0, b0, b1 });
                }
            var t = tris.ToArray();
            var v = verts.ToArray();
            for (int k = 0; k < t.Length; k += 3)
                if (Vector3.Cross(v[t[k + 1]] - v[t[k]], v[t[k + 2]] - v[t[k]]).y < 0) (t[k + 1], t[k + 2]) = (t[k + 2], t[k + 1]);
            MeshObject("Backdrop_Hills", g, v, uvs.ToArray(), t, EnvKit.Mat("ENV_Ground_Grass"), collider: false);
            // woods on the slopes
            var rng = new System.Random(19);
            for (int k = 0; k < 420; k++)
            {
                float a = (float)(rng.NextDouble() * 2 * Mathf.PI);
                float r = Mathf.Lerp(r0 + 70f, 520f, (float)rng.NextDouble());
                float tx = c.x + Mathf.Cos(a) * r, tz = c.y + Mathf.Sin(a) * r;
                float h = H(a, r, Out(tx, tz));
                if (h < 4f) continue;
                EnvKit.Place("ENV_Hill_Tree", g, new Vector3(c.x + Mathf.Cos(a) * r, h - 0.3f, c.y + Mathf.Sin(a) * r), rng.Next(360), Vector3.one * (1.6f + 1.6f * (float)rng.NextDouble()));
            }
            // the town does not end on a lawn (owner points 38-39): dry-stone field walls running out from the edge with
            // hedgerow trees along them, and a few stone barns (cabañas) on the meadows
            var fr = new System.Random(23);
            var fw = new Dictionary<string, string> { { "MI_UnevenBrick", "ENV_Mason_Laja_Gris_G" }, { "MI_RockTrim", "ENV_Dressed_Gris" } };
            for (int k = 0; k < 26; k++)
            {
                float a = (float)(fr.NextDouble() * 2 * Mathf.PI);
                if (Mathf.Abs(Mathf.DeltaAngle(a * Mathf.Rad2Deg, 90f)) < 25f) continue;   // the valley to the port stays open
                float r = r0 + 14f + (float)fr.NextDouble() * 30f, L = 30f + (float)fr.NextDouble() * 60f;
                float bend = (float)(fr.NextDouble() - 0.5) * 0.6f;
                var dir = new Vector2(Mathf.Cos(a + bend), Mathf.Sin(a + bend));
                var start = c + new Vector2(Mathf.Cos(a), Mathf.Sin(a)) * r;
                for (float s0 = 0; s0 < L; s0 += 2f)
                {
                    var q = start + dir * s0;
                    float h = H(Mathf.Atan2(q.y - c.y, q.x - c.x), (q - c).magnitude, Out(q.x, q.y));
                    if (h < -0.5f) continue;
                    EnvKit.Remap(EnvKit.Place("ENV_Retaining_Wall_2x1", g, new Vector3(q.x, h + 0.9f, q.y), Mathf.Atan2(-dir.y, dir.x) * Mathf.Rad2Deg, new Vector3(1.02f, 1f, 0.8f)), fw);
                    if (fr.NextDouble() < 0.28)
                        EnvKit.Place("ENV_Hill_Tree", g, new Vector3(q.x + dir.y * 1.4f, h - 0.2f, q.y - dir.x * 1.4f), fr.Next(360), Vector3.one * (0.8f + 0.7f * (float)fr.NextDouble()));
                }
            }
            for (int k = 0; k < 7; k++)
            {
                float a = (float)(fr.NextDouble() * 2 * Mathf.PI);
                if (Mathf.Abs(Mathf.DeltaAngle(a * Mathf.Rad2Deg, 90f)) < 25f) continue;
                float r = r0 + 30f + (float)fr.NextDouble() * 90f;
                var q = c + new Vector2(Mathf.Cos(a), Mathf.Sin(a)) * r;
                float h = H(a, r, Out(q.x, q.y));
                var barn = new BuildingSpec
                {
                    id = "Cabana_" + k, type = "warehouse", bays = 2 + fr.Next(2), depth = 6, floors = 1 + fr.Next(2), seed = 400 + k, palette = "core_lime_chestnut",
                    ground = "stone", upper = "stone", roof = "gable", chimney = false, exposeLeft = true, exposeRight = true, dress = false, history = false,
                    family = "stone", stone = "ENV_Mason_Mamposteria_Oscura", stoneGround = "ENV_Mason_Mamposteria_Oscura_G", dressed = "ENV_Dressed_Gris",
                    quoins = "none", roofMat = "ENV_Roof_TileMossy", joinery = "ENV_Joinery_Walnut", render = "ENV_Render_Arena_Gastado", renderGround = "ENV_Render_Arena_Gastado_G",
                };
                var go = BuildingAssembler.Build(barn, g);
                go.transform.position = new Vector3(q.x, h - 0.15f, q.y);
                go.transform.rotation = Quaternion.Euler(0, fr.Next(360), 0);
            }
            // the sea to the north, below the town
            var sea = new[] { new Vector3(c.x - 1600, water - 3.5f, c.y + 330), new Vector3(c.x + 1600, water - 3.5f, c.y + 330), new Vector3(c.x + 1600, water - 3.5f, c.y + 2600), new Vector3(c.x - 1600, water - 3.5f, c.y + 2600) };
            MeshObject("Backdrop_Sea", g, sea, sea.Select(p => new Vector2(p.x, p.z) / 20f).ToArray(), new[] { 0, 2, 1, 0, 3, 2 }, EnvKit.Mat("ENV_Water_Port"), collider: false);
        }

        /// <summary>Ground height under (x, z) from the district colliders (ground meshes, decks, stairs).</summary>
        static float GroundY(float x, float z, float fallback)
        {
            var hits = Physics.RaycastAll(new Vector3(x, 80, z), Vector3.down, 200);
            var ground = hits.Where(h => h.collider is MeshCollider && h.collider.name.StartsWith("Ground_") || h.collider.name.Contains("_Deck") || h.collider.name.Contains("_Treads"))
                             .OrderBy(h => h.distance).ToList();
            return ground.Count > 0 ? ground[0].point.y : fallback;
        }

        static bool Inside(List<Vector2> poly, Vector2 p)
        {
            bool c = false;
            for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++)
                if ((poly[i].y > p.y) != (poly[j].y > p.y) && p.x < (poly[j].x - poly[i].x) * (p.y - poly[i].y) / (poly[j].y - poly[i].y) + poly[i].x) c = !c;
            return c;
        }

        static float EdgeDistance(List<Vector2> poly, Vector2 p)
        {
            float best = float.MaxValue;
            for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++)
            {
                var a = poly[j]; var ab = poly[i] - a;
                float t = Mathf.Clamp01(Vector2.Dot(p - a, ab) / Mathf.Max(ab.sqrMagnitude, 1e-6f));
                best = Mathf.Min(best, (a + ab * t - p).magnitude);
            }
            return best;
        }

        /// <summary>Plaza composition (owner audit points 17-19): the main river plaza gets a landmark and sub-spaces
        /// instead of trees on a grid — the fountain with its iron candelabra near the middle (the "I am here"), the
        /// old plane tree with its round bench, a riverside walk of trees in a line along the parapet with benches
        /// facing the water, bar terraces in front of the bars and cafés on the plaza, stone planters with hydrangeas
        /// marking the edges. The smaller plazas get one or two trees of different age, a bench and a lamp. Placement
        /// stays clear of the street lanes crossing a plaza and of the bridge decks.</summary>
        static void DressPlaza(Transform parent, JObject pz, int seed)
        {
            var poly = ((JArray)pz["poly"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
            var g = EnvKit.Group(parent, (string)pz["id"]);
            var rng = new System.Random(seed * 31 + 7);
            var c0 = poly.Aggregate(Vector2.zero, (a, q) => a + q) / poly.Count;
            float xmin = poly.Min(p => p.x), xmax = poly.Max(p => p.x), zmin = poly.Min(p => p.y), zmax = poly.Max(p => p.y);
            var lanes = ((JArray)spec["streets"]).Cast<JObject>()
                .Select(st => (w: (float)st["width"], pts: ((JArray)st["pts"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList())).ToList();
            bool OnLane(Vector2 p, float margin = 1.3f) => lanes.Any(l => (Nearest(l.pts, p) - p).magnitude < l.w / 2f + margin);
            // clearance above the paving (the sphere must not touch the ground collider itself)
            bool Free(Vector2 p, float r) { float rr = Mathf.Min(r, 1.1f); return Physics.OverlapSphere(new Vector3(p.x, GroundY(p.x, p.y, 0) + rr + 0.35f, p.y), rr).Length == 0; }
            var cands = new List<Vector2>();
            for (float x = xmin; x <= xmax; x += 1.0f)
                for (float z = zmin; z <= zmax; z += 1.0f)
                {
                    var p = new Vector2(x, z);
                    if (Inside(poly, p) && EdgeDistance(poly, p) > 2.6f && !OnLane(p)) cands.Add(p);
                }
            var used = new List<(Vector2 p, float r)>();
            bool Clear(Vector2 p, float r) => used.All(u => (u.p - p).magnitude > u.r + r) && EdgeDistance(poly, p) > r * 0.7f && !OnLane(p, r * 0.6f + 0.8f) && Free(p, Mathf.Min(r, 1.5f));
            GameObject At(string module, Vector2 p, float rot, float scale = 1f) =>
                EnvKit.Place(module, g, new Vector3(p.x, GroundY(p.x, p.y, 0), p.y), rot, Vector3.one * scale);
            float Face(Vector2 from, Vector2 to) => Mathf.Atan2(to.x - from.x, to.y - from.y) * Mathf.Rad2Deg;

            if ((string)pz["id"] == "Plaza_Rio")
            {
                // 1. the fountain, on the clear spot nearest the plaza's middle
                var f = cands.Where(p => Clear(p, 5.2f)).OrderBy(p => (p - c0).sqrMagnitude).FirstOrDefault();
                if (f != default)
                {
                    At("ENV_Fountain_Monument", f, 22.5f);
                    used.Add((f, 5.0f));
                }
                // 2. the old plane tree with its ring bench, where the plaza is widest away from the fountain
                var t = cands.Where(p => Clear(p, 4.2f)).OrderByDescending(p => EdgeDistance(poly, p) * 0.6f + (p - f).magnitude * 0.4f).FirstOrDefault();
                if (t != default)
                {
                    At("ENV_Tree_Singular", t, rng.Next(360));
                    used.Add((t, 4.0f));
                }
                // 3. riverside walk: a line of trees along the plaza edge nearest the water, benches facing the river
                var river = ((JArray)spec["river"]["pts"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
                var edge = new List<(Vector2 a, Vector2 b)>();
                for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++)
                {
                    var mid = (poly[i] + poly[j]) / 2f;
                    if ((Nearest(river, mid) - mid).magnitude < 12f) edge.Add((poly[j], poly[i]));
                }
                int k = 0;
                foreach (var (a, b) in edge)
                {
                    float len = (b - a).magnitude;
                    var d = (b - a) / Mathf.Max(len, 1e-3f);
                    var inward = new Vector2(-d.y, d.x);
                    if (!Inside(poly, (a + b) / 2f + inward * 3f)) inward = -inward;
                    for (float s = 3f; s < len - 2f; s += 7f)
                    {
                        var p = a + d * s + inward * 3.2f;
                        if (!Clear(p, 1.6f)) continue;
                        string sp = k % 3 == 1 ? "ENV_Tree_Common_B" : "ENV_Tree_Plaza";
                        At("ENV_Tree_Pit", p, 0);
                        At(sp, p, rng.Next(360), 0.75f + 0.35f * (float)rng.NextDouble());
                        used.Add((p, 1.4f));
                        var bp = p + d * 3.5f - inward * 1.3f;
                        if (Clear(bp, 1.0f))
                        {
                            At(k % 2 == 0 ? "ENV_Bench_Street" : "ENV_Bench_Stone", bp, Face(bp, bp - inward) + 180f);
                            used.Add((bp, 1.0f));
                        }
                        k++;
                    }
                    if (edge.Count > 0 && k > 0)
                    {
                        var lp = a + d * Mathf.Min(len - 1.5f, 1.5f) + inward * 1.8f;
                        if (Clear(lp, 0.5f)) { At("ENV_Lamp_Post", lp, 0); used.Add((lp, 0.5f)); }
                    }
                }
                // 4. terraces in front of the bars and cafés that face the plaza
                foreach (JObject row in (JArray)spec["rows"])
                {
                    if ((string)row["role"] != "plaza") continue;
                    var o = new Vector2((float)row["origin"][0], (float)row["origin"][1]);
                    var dd = new Vector2((float)row["dir"][0], (float)row["dir"][1]);
                    var fz = Quaternion.Euler(0, Mathf.Atan2(-dd.y, dd.x) * Mathf.Rad2Deg, 0) * Vector3.forward;
                    var nn = new Vector2(fz.x, fz.z);
                    foreach (JObject p in (JArray)row["plots"])
                    {
                        if ((bool?)p["wall"] == true || (string)p["type"] != "mixed_commercial") continue;
                        if (rng.NextDouble() < 0.2) continue;
                        float x0 = (float)p["x0"], w = (float)p["w"];
                        int sets = Mathf.Clamp(Mathf.FloorToInt(w / 3.2f), 1, 3);
                        bool barrels = rng.NextDouble() < 0.4;
                        for (int q = 0; q < sets; q++)
                        {
                            // bars take the outer strip of the pavement in front of them, never the middle of the way
                            var tp = o + dd * (x0 + (q + 0.5f) * w / sets) + nn * 1.55f;
                            bool edgeOk = lanes.All(l => (Nearest(l.pts, tp) - tp).magnitude > l.w / 2f - 1.9f);
                            if (!Inside(poly, tp) || !edgeOk || !used.All(u => (u.p - tp).magnitude > u.r + 1.3f) || !Free(tp, 1.0f)) continue;
                            At("ENV_Parasol", tp, 0);
                            At(barrels ? "ENV_Prop_Barrel" : "ENV_Cafe_Table", tp, rng.Next(360));
                            for (int c = 0; c < (barrels ? 2 : 3); c++)
                            {
                                float ang = c * 2.1f + (float)rng.NextDouble();
                                var cp = tp + new Vector2(Mathf.Cos(ang), Mathf.Sin(ang)) * 0.75f;
                                At(barrels ? "ENV_Prop_Stool" : "ENV_Cafe_Chair", cp, Face(cp, tp) + 180f + rng.Next(-20, 20));
                            }
                            used.Add((tp, 1.4f));
                        }
                    }
                }
                // 5. stone planters with hydrangeas marking the edges of the free floor
                int planters = 0;
                foreach (var p in cands.OrderBy(_ => rng.Next()))
                {
                    if (planters >= 5) break;
                    if (EdgeDistance(poly, p) > 4.5f || !Clear(p, 1.2f)) continue;
                    At("ENV_Trough_Stone", p, rng.Next(0, 4) * 90 + 10);
                    var h = At("ENV_Plant_Hydrangea", p + new Vector2(0, 0), rng.Next(360), 0.85f);
                    h.transform.position += Vector3.up * 0.36f;
                    EnvKit.Remap(h, new Dictionary<string, string> { { "ENV_Flower_Blue", new[] { "ENV_Flower_Blue", "ENV_Flower_Pink", "ENV_Flower_White" }[rng.Next(3)] } });
                    used.Add((p, 1.5f));
                    planters++;
                }
                // 6. a litter bin and a bike rack where people pass
                foreach (var (m, r) in new[] { ("ENV_Bin_Street", 0.5f), ("ENV_Bike_Rack", 1.4f), ("ENV_Bin_Street", 0.5f) })
                {
                    var p = cands.Where(q => EdgeDistance(poly, q) < 4f && Clear(q, r)).OrderBy(_ => rng.Next()).FirstOrDefault();
                    if (p != default) { At(m, p, rng.Next(0, 4) * 90); used.Add((p, r)); }
                }
                return;
            }

            // smaller plazas: one or two trees of different age, a bench under them, a lamp
            float area = 0;
            for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++) area += (poly[j].x + poly[i].x) * (poly[j].y - poly[i].y);
            area = Mathf.Abs(area) / 2f;
            int trees = area > 120 ? 2 : 1;
            string[] kinds = { "ENV_Tree_Plaza", "ENV_Tree_Common_A", "ENV_Tree_Common_C" };
            for (int n = 0; n < trees; n++)
            {
                var p = cands.Where(q => Clear(q, 2.2f)).OrderBy(q => (q - c0).sqrMagnitude * (0.5f + (float)rng.NextDouble())).FirstOrDefault();
                if (p == default) break;
                At("ENV_Tree_Pit", p, 0);
                At(kinds[rng.Next(kinds.Length)], p, rng.Next(360), n == 0 ? 1.0f + 0.25f * (float)rng.NextDouble() : 0.65f + 0.2f * (float)rng.NextDouble());
                used.Add((p, 2.2f));
                var toC = (c0 - p).normalized;
                var b = p + toC * 1.6f;
                if (Clear(b, 0.9f)) { At(rng.NextDouble() < 0.5 ? "ENV_Bench_Street" : "ENV_Bench_Stone", b, Face(b, c0) + 180f); used.Add((b, 0.9f)); }
            }
            var lampAt = poly.OrderBy(v => (v - c0).sqrMagnitude).Select(v => v + (c0 - v).normalized * 2.2f).FirstOrDefault(q => Inside(poly, q) && Clear(q, 0.4f));
            if (lampAt != default) At("ENV_Lamp_Post", lampAt, 0);
        }

        /// <summary>What a street has under and beside it (owner points 15-16): manhole covers and gully grates at
        /// intervals, a recycling point at a few widenings, bollards where the spine meets the plaza, the pedestrian
        /// zone sign where cars would come in. Sparse, and never on stairs or bridges.</summary>
        static void StreetFurniture(Transform root)
        {
            var g = EnvKit.Group(root, "StreetFurniture");
            Physics.SyncTransforms();
            foreach (JObject st in (JArray)spec["streets"])
            {
                string role = (string)st["role"];
                if (role == "steps" || role == "bridge" || role == "footbridge") continue;
                var pts = ((JArray)st["pts"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList();
                float w = (float)st["width"];
                float acc = 6f + 8f * Hash01(pts[0].x, pts[0].y, 61);
                for (int i = 0; i + 1 < pts.Count; i++)
                {
                    var a = pts[i]; var b = pts[i + 1];
                    float len = (b - a).magnitude;
                    var d = (b - a) / Mathf.Max(len, 1e-3f);
                    var n = new Vector2(-d.y, d.x);
                    for (float t = acc; t < len; t += 15f + 9f * Hash01(a.x + t, a.y, 62))
                    {
                        var c = a + d * t;
                        bool grate = Hash01(c.x, c.y, 63) < 0.55f;
                        var p = grate ? c + n * (w / 2f - 0.55f) * (Hash01(c.x, c.y, 64) < 0.5f ? 1 : -1) : c + n * (Hash01(c.x, c.y, 65) - 0.5f) * 0.6f;
                        float y = GroundY(p.x, p.y, float.NaN);
                        if (float.IsNaN(y)) continue;
                        EnvKit.Place(grate ? "ENV_Drain_Grate" : "ENV_Manhole", g, new Vector3(p.x, y + 0.004f, p.y), Mathf.Atan2(d.x, d.y) * Mathf.Rad2Deg);
                    }
                    acc = 0f;
                }
            }
            // recycling points at the small plazas, off the walking lines that cross them (route probe: a set of bins
            // on the lane through the Plazuela Oeste stalled the player)
            var lanes = ((JArray)spec["streets"]).Cast<JObject>()
                .Select(st => (w: (float)st["width"], pts: ((JArray)st["pts"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList())).ToList();
            bool OffLanes(Vector2 p) => lanes.All(l => (Nearest(l.pts, p) - p).magnitude > l.w / 2f + 1.6f);
            foreach (var id in new[] { "Plazuela_Oeste", "Cabeza_Puente", "Plazuela_Fuente" })
            {
                var pz = ((JArray)spec["plazas"]).Cast<JObject>().FirstOrDefault(q => (string)q["id"] == id);
                if (pz == null) continue;
                var poly = ((JArray)pz["poly"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
                var c0 = poly.Aggregate(Vector2.zero, (x, q) => x + q) / poly.Count;
                for (int k = 0; k < 24; k++)
                {
                    float ang = k * 0.9f;
                    var p = c0 + new Vector2(Mathf.Cos(ang), Mathf.Sin(ang)) * (2f + k * 0.25f);
                    if (!Inside(poly, p) || EdgeDistance(poly, p) < 1.2f || !OffLanes(p)) continue;
                    float y = GroundY(p.x, p.y, float.NaN);
                    if (float.IsNaN(y) || Physics.OverlapBox(new Vector3(p.x, y + 1.0f, p.y), new Vector3(2.0f, 0.6f, 0.8f)).Length > 0) continue;
                    EnvKit.Place("ENV_Recycling_Bins", g, new Vector3(p.x, y, p.y), Mathf.Atan2(c0.x - p.x, c0.y - p.y) * Mathf.Rad2Deg);
                    break;
                }
            }
            // where the spine enters the town: pedestrian zone sign and a pair of bollards
            var spine = ((JArray)spec["streets"]).Cast<JObject>().FirstOrDefault(q => (string)q["id"] == "Espina_E");
            if (spine != null)
            {
                var a = new Vector2((float)spine["pts"][0][0], (float)spine["pts"][0][1]);
                var b = new Vector2((float)spine["pts"][1][0], (float)spine["pts"][1][1]);
                var d = (b - a).normalized;
                var n = new Vector2(-d.y, d.x);
                float w = (float)spine["width"];
                var s0 = a + d * 3f + n * (w / 2f - 0.5f);
                EnvKit.Place("ENV_Sign_NoEntry", g, new Vector3(s0.x, GroundY(s0.x, s0.y, 0), s0.y), Mathf.Atan2(-d.x, -d.y) * Mathf.Rad2Deg);
                foreach (var off in new[] { -1.2f, 1.2f })
                {
                    var bp = a + d * 4.5f + n * off;
                    EnvKit.Place("ENV_Bollard_Street", g, new Vector3(bp.x, GroundY(bp.x, bp.y, 0), bp.y), 0);
                }
            }
        }

        /// <summary>Point at fraction t (0..1) along a street centreline of the spec, at street level (x, y, z).</summary>
        public static Vector3 StreetPoint(string streetId, float t)
        {
            if (spec == null) spec = JObject.Parse(EnvKit.ReadText($"{DistrictSpecs}/{id ?? "ENV01_Casco_District"}.json"));
            var s = ((JArray)spec["streets"]).Cast<JObject>().First(x => (string)x["id"] == streetId);
            var pts = ((JArray)s["pts"]).Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
            float total = 0;
            for (int i = 0; i + 1 < pts.Count; i++) total += Vector3.Distance(pts[i], pts[i + 1]);
            float want = Mathf.Clamp01(t) * total;
            for (int i = 0; i + 1 < pts.Count; i++)
            {
                float l = Vector3.Distance(pts[i], pts[i + 1]);
                if (want <= l || i == pts.Count - 2) return Vector3.Lerp(pts[i], pts[i + 1], l > 0 ? Mathf.Clamp01(want / l) : 0);
                want -= l;
            }
            return pts[0];
        }

        /// <summary>Eye-level capture along a street: eye at fraction <paramref name="from"/> (1.7 m up, optionally
        /// shifted sideways), looking at fraction <paramref name="to"/> of the same or another street.</summary>
        public static string CaptureStreet(string file, string street, float from, string lookStreet, float to, float side = 0f, float fov = 60f)
        {
            var eye = StreetPoint(street, from);
            var look = StreetPoint(lookStreet ?? street, to);
            var d = look - eye;
            d.y = 0;
            var s = new Vector3(-d.z, 0, d.x).normalized * side;
            return EnvPreview.Capture(file, eye + s + Vector3.up * 1.7f, look + Vector3.up * 2.0f, fov);
        }

        static Vector2 Nearest(List<Vector2> line, Vector2 p)
        {
            var best = line[0];
            float bd = float.MaxValue;
            for (int i = 0; i + 1 < line.Count; i++)
            {
                var a = line[i];
                var ab = line[i + 1] - a;
                float t = Mathf.Clamp01(Vector2.Dot(p - a, ab) / Mathf.Max(ab.sqrMagnitude, 1e-6f));
                var q = a + ab * t;
                float d = (q - p).sqrMagnitude;
                if (d < bd) { bd = d; best = q; }
            }
            return best;
        }

        /// <summary>Stone bridge: a deck slab with setts on top at the bank levels, masonry sides and a stone parapet
        /// each side; the span over the channel reads as a low arch (a stepped soffit). Deck follows the street line.</summary>
        static void Bridge(Transform parent, JObject br, float water)
        {
            var pts = ((JArray)br["pts"]).Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
            float w = (float)br["width"];
            bool foot = (string)br["role"] == "footbridge";
            var g = EnvKit.Group(parent, (string)br["id"]);
            var a = pts[0];
            var b = pts[pts.Count - 1];
            var d = new Vector3(b.x - a.x, 0, b.z - a.z);
            float len = d.magnitude;
            d /= len;
            var side = new Vector3(-d.z, 0, d.x);
            // deck: top quad (setts) + sides and soffit (stone), thickness grows towards the banks (arch read)
            float thick = 0.3f;  // the stone arch module (ENV_Bridge_Arch) carries the body; this is the paved deck
            var verts = new List<Vector3>();
            var tris = new List<int>();
            var uvs = new List<Vector2>();
            void Quad(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 outDir)
            {
                int i0 = verts.Count;
                verts.AddRange(new[] { p0, p1, p2, p3 });
                uvs.AddRange(new[] { new Vector2(p0.x + p0.y, p0.z) / 2f, new Vector2(p1.x + p1.y, p1.z) / 2f, new Vector2(p2.x + p2.y, p2.z) / 2f, new Vector2(p3.x + p3.y, p3.z) / 2f });
                bool flip = Vector3.Dot(Vector3.Cross(p1 - p0, p2 - p0), outDir) < 0;
                tris.AddRange(flip ? new[] { i0, i0 + 2, i0 + 1, i0, i0 + 3, i0 + 2 } : new[] { i0, i0 + 1, i0 + 2, i0, i0 + 2, i0 + 3 });
            }
            int n = 12;
            var top = new List<(Vector3 l, Vector3 r, float soffit)>();
            for (int k = 0; k <= n; k++)
            {
                float t = k / (float)n;
                var c = Vector3.Lerp(a, b, t) + Vector3.up * 0.02f;
                float arch = thick;
                top.Add((c + side * w / 2, c - side * w / 2, arch));
            }
            var deckV = new List<Vector3>();
            for (int k = 0; k < n; k++)
            {
                var (l0, r0, s0) = top[k];
                var (l1, r1, s1) = top[k + 1];
                Quad(l0, l1, r1, r0, Vector3.up);                                                                      // deck top
                Quad(l0 - Vector3.up * s0, l1 - Vector3.up * s1, l1, l0, side);                                         // left side
                Quad(r0, r1, r1 - Vector3.up * s1, r0 - Vector3.up * s0, -side);                                        // right side
                Quad(r0 - Vector3.up * s0, r1 - Vector3.up * s1, l1 - Vector3.up * s1, l0 - Vector3.up * s0, Vector3.down); // soffit
            }
            var vs = verts.ToArray();
            var ts = tris.ToArray();
            MeshObject((string)br["id"] + "_Deck", g, vs, uvs.ToArray(), ts, EnvKit.Mat("ENV_Ground_Setts_Warm"), collider: true);
            // parapets: masonry under a rounded dressed coping, both sides; a lamp at each end of the road bridge
            int np = Mathf.Max(1, Mathf.RoundToInt(len / 2f));
            float yaw = Mathf.Atan2(-d.z, d.x) * Mathf.Rad2Deg;
            var map = new Dictionary<string, string> { { "MI_UnevenBrick", "ENV_Mason_Mamposteria_Gris" }, { "MI_RockTrim", "ENV_Dressed_Gris" } };
            for (int k = 0; k < np; k++)
            {
                var c = Vector3.Lerp(a, b, (k + 0.5f) / np);
                foreach (var sgn in new[] { 1f, -1f })
                {
                    var at = c + side * sgn * (w / 2f - 0.24f);
                    EnvKit.Remap(EnvKit.Place("ENV_Parapet_Stone_2m", g, at, yaw + (sgn > 0 ? 0 : 180), new Vector3(len / np / 2f + 0.01f, 1f, 1f)), map);
                }
            }
            if (!foot)
                foreach (var (end, sgn) in new[] { (a + d * 0.6f, 1f), (b - d * 0.6f, -1f) })
                    EnvKit.Place("ENV_Lamp_Post", g, end + side * sgn * (w / 2f - 0.24f) + Vector3.up * 1.0f, yaw);
        }

        /// <summary>Rocks in the river: along the foot of the walls and a few mid-stream, partly out of the water, so the
        /// current has something to break on (foam) and the channel reads as a river, not a pool.</summary>
        const float RiverDepth = 0.65f;

        static void RiverRocks(Transform rv, List<Vector2> channel, List<Vector2> centre, float water, float width)
        {
            var g = EnvKit.Group(rv, "Rocks");
            string[] rocks = { "ENV_Rock_A", "ENV_Rock_B", "ENV_Rock_C" };
            int n = 0;
            for (int i = 0; i + 1 < centre.Count; i++)
            {
                var a = centre[i]; var b = centre[i + 1];
                float len = (b - a).magnitude;
                var d = (b - a) / len;
                var nrm = new Vector2(-d.y, d.x);
                for (float s = 0; s < len; s += 2.6f)
                {
                    var c = a + d * s;
                    float h = Hash01(c.x, c.y, 5);
                    if (h > 0.62f) continue;
                    float lat = (Hash01(c.x, c.y, 6) < 0.8f ? (Hash01(c.x, c.y, 8) < 0.5f ? -1f : 1f) * (width / 2f - 0.9f) : (Hash01(c.x, c.y, 9) - 0.5f) * width * 0.5f);
                    var p = c + nrm * lat + d * (Hash01(c.x, c.y, 10) - 0.5f) * 2f;
                    if (!Inside(channel, p)) continue;
                    // rocks rest on the bed; the bigger ones break the surface (kit rock: 2.3 m high, base 0.27 below pivot)
                    float sc = 0.22f + 0.26f * Hash01(c.x, c.y, 12);
                    EnvKit.Place(rocks[(int)(h * 30) % 3], g, new Vector3(p.x, water - RiverDepth + 0.27f * sc - 0.08f, p.y), h * 720f, Vector3.one * sc);
                    n++;
                }
            }
        }

        /// <summary>Life on one channel-wall piece: an occasional drain with its stain, ferns at the water line, ivy
        /// hanging from the coping, weeds on top. Frame: wall face towards the water (+z of yaw).</summary>
        static void RiverWallLife(Transform rv, Vector3 top, float yaw, float water, float len, float h)
        {
            var g = EnvKit.Group(rv, "WallLife");
            var rot = Quaternion.Euler(0, yaw, 0);
            Vector3 P(float x, float y, float z) => top + rot * new Vector3(x, 0, z) + Vector3.up * (y - top.y);
            float face = 0.0f;
            if (h < 0.22f)
            {
                float y = water + 0.8f + 0.9f * Hash01(top.x, top.z, 21);
                EnvKit.Place("ENV_Drain_Outlet", g, P(0, y, face), yaw);
                var st = EnvKit.Place("ENV_Stain_Quad", g, P(0, water, face - 0.09f), yaw, new Vector3(0.9f, y - water + 0.1f, 1));
                EnvKit.Remap(st, new Dictionary<string, string> { { "ENV_Stain_Downpipe", h < 0.1f ? "ENV_Stain_Rust" : "ENV_Stain_Algae" } });
            }
            if (Hash01(top.x, top.z, 22) < 0.3f)
                EnvKit.Place("ENV_Plant_Fern", g, P((Hash01(top.x, top.z, 23) - 0.5f) * len * 0.6f, water + 0.05f, face + 0.25f), Hash01(top.x, top.z, 24) * 360f, Vector3.one * (0.06f + 0.05f * Hash01(top.x, top.z, 25)));
            if (Hash01(top.x, top.z, 26) < 0.22f)
                EnvKit.Place("Prop_Vine" + (1 + (int)(Hash01(top.x, top.z, 27) * 3)), g, P((Hash01(top.x, top.z, 28) - 0.5f) * len * 0.5f, top.y - 0.35f, face + 0.02f), yaw);
            if (Hash01(top.x, top.z, 29) < 0.18f)
                EnvKit.Place("ENV_Weeds_Grass", g, P((Hash01(top.x, top.z, 30) - 0.5f) * len * 0.6f, top.y, face - 0.4f), Hash01(top.x, top.z, 31) * 360f, Vector3.one * 0.6f);
        }

        /// <summary>Stepped lane (escalinata): long treads with low risers between the two street levels, stone
        /// nosings, a skirt down the open sides. One mesh per stair (treads: flags; risers: rock trim).</summary>
        static void Stairs(Transform parent, JObject s)
        {
            var pts = ((JArray)s["pts"]).Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
            float w = (float)s["width"];
            var a = pts[0];
            var b = pts[pts.Count - 1];
            if (a.y > b.y) (a, b) = (b, a);
            float rise = b.y - a.y;
            var d = new Vector3(b.x - a.x, 0, b.z - a.z);
            float len = d.magnitude;
            d /= len;
            var side = new Vector3(-d.z, 0, d.x) * (w / 2f + 0.3f);
            int steps = Mathf.Max(2, Mathf.CeilToInt(rise / 0.16f));
            float tread = len / steps, riser = rise / steps;
            var tv = new List<Vector3>(); var tt = new List<int>(); var tu = new List<Vector2>();
            var rv = new List<Vector3>(); var rt = new List<int>(); var ru = new List<Vector2>();
            void Quad(List<Vector3> V, List<int> T, List<Vector2> U, Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 outDir)
            {
                int i0 = V.Count;
                bool vertical = Mathf.Abs(outDir.y) < 0.5f;
                V.AddRange(new[] { p0, p1, p2, p3 });
                var across = Vector3.Cross(Vector3.up, outDir).normalized;
                foreach (var p in new[] { p0, p1, p2, p3 }) U.Add(vertical ? new Vector2(Vector3.Dot(p, across), p.y) / 2f : new Vector2(p.x, p.z) / 2f);
                bool flip = Vector3.Dot(Vector3.Cross(p1 - p0, p2 - p0), outDir) < 0;
                T.AddRange(flip ? new[] { i0, i0 + 2, i0 + 1, i0, i0 + 3, i0 + 2 } : new[] { i0, i0 + 1, i0 + 2, i0, i0 + 2, i0 + 3 });
            }
            for (int k = 0; k < steps; k++)
            {
                var c0 = a + d * (tread * k);
                var c1 = a + d * (tread * (k + 1));
                float y = a.y + riser * (k + 1);
                var l0 = new Vector3(c0.x, y, c0.z) + side; var r0 = new Vector3(c0.x, y, c0.z) - side;
                var l1 = new Vector3(c1.x, y, c1.z) + side; var r1 = new Vector3(c1.x, y, c1.z) - side;
                Quad(tv, tt, tu, l0, l1, r1, r0, Vector3.up);                                            // tread
                var lb = l0 - Vector3.up * riser; var rb = r0 - Vector3.up * riser;
                Quad(rv, rt, ru, lb, l0, r0, rb, -d);                                                    // riser (faces down-slope)
                float skirt = y - a.y + 0.4f;
                Quad(rv, rt, ru, l1 - Vector3.up * skirt, l1, l0, l0 - Vector3.up * skirt, side);        // open side left
                Quad(rv, rt, ru, r0 - Vector3.up * skirt, r0, r1, r1 - Vector3.up * skirt, -side);       // open side right
            }
            var g = EnvKit.Group(parent, (string)s["id"]);
            MeshObject((string)s["id"] + "_Treads", g, tv.ToArray(), tu.ToArray(), tt.ToArray(), EnvKit.Mat("ENV_Ground_Flag_Light"), collider: true);
            MeshObject((string)s["id"] + "_Risers", g, rv.ToArray(), ru.ToArray(), rt.ToArray(), EnvKit.Mat("MI_RockTrim"), collider: true);
        }

        /// <summary>Ear clipping for a simple polygon (the river channel), returns triangle indices.</summary>
        static int[] EarClip(List<Vector2> poly)
        {
            var idx = Enumerable.Range(0, poly.Count).ToList();
            float area = 0;
            for (int i = 0; i < poly.Count; i++) area += poly[i].x * poly[(i + 1) % poly.Count].y - poly[(i + 1) % poly.Count].x * poly[i].y;
            if (area < 0) idx.Reverse();
            var tris = new List<int>();
            int guard = 0;
            while (idx.Count > 3 && guard++ < 10000)
            {
                bool clipped = false;
                for (int i = 0; i < idx.Count; i++)
                {
                    int i0 = idx[(i + idx.Count - 1) % idx.Count], i1 = idx[i], i2 = idx[(i + 1) % idx.Count];
                    var a = poly[i0]; var b = poly[i1]; var c = poly[i2];
                    if ((b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x) <= 0) continue;  // reflex
                    bool inside = false;
                    foreach (var j in idx)
                    {
                        if (j == i0 || j == i1 || j == i2) continue;
                        if (InTri(poly[j], a, b, c)) { inside = true; break; }
                    }
                    if (inside) continue;
                    tris.AddRange(new[] { i0, i1, i2 });
                    idx.RemoveAt(i);
                    clipped = true;
                    break;
                }
                if (!clipped) break;
            }
            if (idx.Count == 3) tris.AddRange(idx);
            return tris.ToArray();
        }

        static bool InTri(Vector2 p, Vector2 a, Vector2 b, Vector2 c)
        {
            float d1 = (p.x - b.x) * (a.y - b.y) - (a.x - b.x) * (p.y - b.y);
            float d2 = (p.x - c.x) * (b.y - c.y) - (b.x - c.x) * (p.y - c.y);
            float d3 = (p.x - a.x) * (c.y - a.y) - (c.x - a.x) * (p.y - a.y);
            bool neg = d1 < 0 || d2 < 0 || d3 < 0, pos = d1 > 0 || d2 > 0 || d3 > 0;
            return !(neg && pos);
        }
    }
}
