using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

namespace JuegoDef.Env
{
    /// <summary>
    /// Step 7 of the ENV factory: builds a whole district from the spec generated by
    /// Tools/env_district_skeleton.py (Env/Specs/districts/&lt;id&gt;.json): heightfield ground meshes by paving zone,
    /// one facade row per block edge (the street assembler's party-wall/quoin rules, buildings on the terrain with a
    /// stone base where the ground falls away), garden walls, the channelled river with its walls, parapets and bridges,
    /// stairs, and the GC2 player. Builds in chunks (Begin, BuildRows(from, count)..., Finish) so the operator never
    /// holds the Editor in one long call. Menu: JuegoDef &gt; ENV &gt; 7 Build District (CASCO).
    /// </summary>
    public static class EnvDistrict
    {
        public const string DistrictSpecs = EnvKit.Specs + "/districts";
        static JObject spec;
        static string id;
        static Dictionary<string, JObject> units;

        /// <summary>Paving zone -> material and UV tile size (m). Kit floor textures repeat every 2 m tile.</summary>
        static readonly Dictionary<string, (string mat, float tile)> GroundMats = new Dictionary<string, (string, float)>
        {
            { "core", ("ENV_Ground_Canto", 1.4f) },          // canto rodado: smaller, darker river cobbles
            { "core_band", ("ENV_Ground_Flag_Light", 2f) },
            { "strip", ("ENV_Ground_Flag_Light", 2.6f) },    // central strip of big flags (casco street, owner photo)
            { "lane", ("ENV_Ground_Canto_Old", 1.4f) },
            { "plaza", ("ENV_Ground_Flag_Warm", 2.4f) },
            { "yard", ("ENV_Ground_Grass", 4f) },
            { "huerta", ("ENV_Ground_Earth", 6f) },
            { "outer", ("ENV_Ground_Grass", 4f) },
        };

        static Transform Root { get { EnsureSpec(); return GameObject.Find(id)?.transform; } }

        /// <summary>Static state does not survive a domain reload between chunked calls: recover the district id from
        /// the open scene (its root object) and reload the spec and the unit library.</summary>
        static void EnsureSpec()
        {
            if (spec != null && units != null && id != null) return;
            if (id == null)
                id = UnityEngine.SceneManagement.SceneManager.GetActiveScene().GetRootGameObjects()
                        .Select(g => g.name).FirstOrDefault(n => n.StartsWith("ENV01_") && System.IO.File.Exists($"{DistrictSpecs}/{n}.json"));
            if (id == null) throw new System.InvalidOperationException("JD_DISTRICT_NO_STATE: call Begin(id) first");
            spec = JObject.Parse(EnvKit.ReadText($"{DistrictSpecs}/{id}.json"));
            units = JObject.Parse(EnvKit.ReadText(EnvKit.Specs + "/units.json"))["units"].ToDictionary(u => (string)u["id"], u => (JObject)u);
        }
        static string MeshFolder => $"{EnvKit.Derived}/District/{id}";

        [MenuItem("JuegoDef/ENV/7 Build District (CASCO)")]
        public static void BuildMenu()
        {
            Debug.Log(Begin("ENV01_Casco_District"));
            Debug.Log(BuildRows(0, int.MaxValue));
            Debug.Log(Finish());
        }

        public static string Begin(string districtId)
        {
            id = districtId;
            spec = JObject.Parse(EnvKit.ReadText($"{DistrictSpecs}/{id}.json"));
            EnvKit.ClearCache();
            EnvClearance.ClearCache();
            BuildingAssembler.ReloadGrammar();
            units = JObject.Parse(EnvKit.ReadText(EnvKit.Specs + "/units.json"))["units"].ToDictionary(u => (string)u["id"], u => (JObject)u);
            var stage = EnvPreview.NewStage(id, ground: false);
            Object.DestroyImmediate(stage.gameObject);
            var root = new GameObject(id).transform;
            int tris = BuildGround(root);
            return $"JD_DISTRICT_BEGIN {id} ground tris={tris} rows={((JArray)spec["rows"]).Count}";
        }

        // ------------------------------------------------------------------ ground

        static int BuildGround(Transform root)
        {
            EnvKit.EnsureFolder(MeshFolder);
            var g = EnvKit.Group(root, "Ground");
            int total = 0;
            foreach (var kv in (JObject)spec["ground"])
            {
                var v = (JArray)kv.Value["v"];
                var t = ((JArray)kv.Value["t"]).Select(x => (int)x).ToArray();
                var (mat, tile) = GroundMats.TryGetValue(kv.Key, out var gm) ? gm : ("ENV_Ground_Patch", 2f);
                var verts = new Vector3[v.Count];
                var uvs = new Vector2[v.Count];
                for (int i = 0; i < v.Count; i++)
                {
                    verts[i] = new Vector3((float)v[i][0], (float)v[i][1], (float)v[i][2]);
                    uvs[i] = new Vector2(verts[i].x / tile, verts[i].z / tile);
                }
                for (int k = 0; k < t.Length; k += 3)
                    if (Vector3.Cross(verts[t[k + 1]] - verts[t[k]], verts[t[k + 2]] - verts[t[k]]).y < 0)
                        (t[k + 1], t[k + 2]) = (t[k + 2], t[k + 1]);  // front faces up (Unity: clockwise from above)
                var go = MeshObject("Ground_" + kv.Key, g, verts, uvs, t, EnvKit.Mat(mat), collider: true);
                total += t.Length / 3;
            }
            return total;
        }

        static GameObject MeshObject(string name, Transform parent, Vector3[] verts, Vector2[] uvs, int[] tris, Material mat, bool collider)
        {
            var mesh = new Mesh { name = $"{id}_{name}", indexFormat = verts.Length > 65000 ? IndexFormat.UInt32 : IndexFormat.UInt16 };
            mesh.SetVertices(verts);
            mesh.SetUVs(0, uvs);
            mesh.SetTriangles(tris, 0);
            mesh.RecalculateNormals();
            mesh.RecalculateTangents();
            mesh.RecalculateBounds();
            var path = $"{MeshFolder}/{name}.asset";
            AssetDatabase.DeleteAsset(path);
            AssetDatabase.CreateAsset(mesh, path);
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            go.AddComponent<MeshFilter>().sharedMesh = mesh;
            go.AddComponent<MeshRenderer>().sharedMaterial = mat;
            if (collider) go.AddComponent<MeshCollider>().sharedMesh = mesh;
            GameObjectUtility.SetStaticEditorFlags(go, (StaticEditorFlags)~0);
            return go;
        }

        // ------------------------------------------------------------------ rows

        public static string BuildRows(int from, int count)
        {
            EnsureSpec();
            var root = Root;
            var rows = (JArray)spec["rows"];
            var rg = EnvKit.Group(root, "Rows");
            int buildings = 0, walls = 0, end = (int)Mathf.Min(rows.Count, (long)from + count);
            var sw = System.Diagnostics.Stopwatch.StartNew();
            for (int r = from; r < end; r++)
            {
                var row = (JObject)rows[r];
                var frame = new GameObject((string)row["id"]).transform;
                frame.SetParent(rg, false);
                frame.localPosition = new Vector3((float)row["origin"][0], 0, (float)row["origin"][1]);
                frame.localRotation = Quaternion.Euler(0, Mathf.Atan2(-(float)row["dir"][1], (float)row["dir"][0]) * Mathf.Rad2Deg, 0);
                var placed = new List<EnvStreet.Placed>();
                var plots = ((JArray)row["plots"]).Cast<JObject>().ToList();
                for (int k = 0; k < plots.Count; k++)
                {
                    var p = plots[k];
                    if ((bool?)p["wall"] == true) { placed.Add(null); continue; }
                    var bs = SpecOf(p, $"{row["id"]}_{k}");
                    float w = (float)p["w"];
                    placed.Add(new EnvStreet.Placed { spec = bs, x0 = (float)p["x0"], width = w, scale = w / (bs.bays * 2f), setback = (float?)p["setback"] ?? 0f, y = (float)p["y"] });
                }
                EnvStreet.ResolveNeighbours(placed, (JObject)row["ends"]);
                foreach (var p in placed.Where(p => p != null))
                {
                    var go = BuildingAssembler.Build(p.spec, frame);
                    go.transform.localPosition = new Vector3(p.x0, p.y, -p.setback);
                    if (Mathf.Abs(p.scale - 1f) > 0.001f) go.transform.localScale = new Vector3(p.scale, 1, 1);
                    buildings++;
                }
                foreach (var p in plots.Where(p => (bool?)p["wall"] == true))
                {
                    GardenWall(frame, p);
                    walls++;
                }
            }
            return $"JD_DISTRICT_ROWS {from}..{end - 1} buildings={buildings} walls={walls} ms={sw.ElapsedMilliseconds}";
        }

        static readonly Dictionary<int, string[]> CasonaRows = new Dictionary<int, string[]>
        {
            // few openings: arched portal with the shield above it, windows on the principal floor, the top floor opening
            // onto the solana through its one door
            { 4, new[] { "WPAP", "PWPW", "wPNw" } },
            { 5, new[] { "PWAWP", "WPPPW", "PwNwP" } },
        };

        static BuildingSpec SpecOf(JObject p, string name)
        {
            BuildingSpec bs;
            if (p["unit"] != null)
            {
                bs = ((JObject)units[(string)p["unit"]]["building"]).ToObject<BuildingSpec>();
                bs.floors = (int?)p["floors"] ?? bs.floors;
            }
            else
                bs = new BuildingSpec
                {
                    type = (string)p["type"], bays = (int)p["bays"], depth = (int)p["depth"], floors = (int)p["floors"],
                    seed = (int?)p["seed"] ?? 1, palette = (string)p["palette"], ground = (string)p["ground"] ?? "", upper = (string)p["upper"] ?? "plaster",
                };
            bs.id = name;
            if (p["era"] != null) bs.era = (string)p["era"];
            if (p["rows"] is JArray rows) bs.rows = rows.Select(x => (string)x).ToArray();
            if (p["awning"] != null) bs.awning = (string)p["awning"];
            bs.solana = (bool?)p["solana"] == true;
            bs.surrounds = (bool?)p["surrounds"] == true;
            bs.escudo = (bool?)p["escudo"] == true;
            if ((bool?)p["casona"] == true)
            {
                bs.era = "old";
                bs.ground = "stone";
                bs.solana = bs.floors >= 3;
                bs.escudo = true;
                bs.surrounds = true;
                if (CasonaRows.TryGetValue(bs.bays, out var cr)) bs.rows = cr.Take(bs.floors).ToArray();
            }
            bs.basement = (float?)p["basement"] ?? 0f;
            // shop life (owner photos): striped awnings and wrought-iron hanging signs on a good share of the shops
            var lrng = new System.Random(bs.seed * 13 + 7);
            if (bs.type == "mixed_commercial" && string.IsNullOrEmpty(bs.awning) && lrng.NextDouble() < 0.55)
                bs.awning = new[] { "ENV_Canvas_Green", "ENV_Canvas_Red", "ENV_Canvas_Cream" }[lrng.Next(3)];
            if ((bs.type == "mixed_commercial" || bs.type == "lodging") && lrng.NextDouble() < 0.5) bs.sign = "bracket";
            return bs;
        }

        /// <summary>Rubble garden wall (huertas) along a row stretch, stepping with the ground every 2 m; a timber gate
        /// where the spec asks for one. "tall" walls close a street wall where a block was too thin for a building.</summary>
        static void GardenWall(Transform frame, JObject p)
        {
            var g = EnvKit.Group(frame, "Walls");
            float x0 = (float)p["x0"], w = (float)p["w"];
            var ys = ((JArray)p["ys"])?.Select(v => (float)v).ToArray() ?? new[] { 0f };
            bool tall = (bool?)p["tall"] == true;
            float h = tall ? 4.6f : 2.2f;
            float gate = (float?)p["gate"] ?? -10f;
            int n = Mathf.Max(1, Mathf.CeilToInt(w / 2f - 0.01f));
            float seg = w / n;
            for (int k = 0; k < n; k++)
            {
                float xc = x0 + seg * (k + 0.5f);
                float y = ys[Mathf.Clamp(Mathf.RoundToInt((xc - x0) / 2f), 0, ys.Length - 1)];
                if (gate > 0 && Mathf.Abs(xc - (x0 + gate)) < seg / 2f)
                {
                    // plank gate into the huerta (the kit timber fence is a banned alpine cue)
                    EnvKit.Place("ENV_Gate_Timber", g, new Vector3(xc, y, -0.05f), 0, new Vector3(seg / 1.6f, 0.8f, 1));
                    continue;
                }
                EnvKit.Place("ENV_Retaining_Wall_2x2", g, new Vector3(xc, y + h, -0.1f), 0, new Vector3(seg / 2f, (h + 0.6f) / 2f, 0.6f));
            }
        }

        // ------------------------------------------------------------------ river, bridges, stairs, player

        public static string Finish()
        {
            EnsureSpec();
            var root = Root;
            var river = (JObject)spec["river"];
            var rv = EnvKit.Group(root, "River");
            float water = (float)river["water"];
            // water surface over the channel polygon (fan triangulation of a simple polygon is not safe: ear clipping)
            var ch = ((JArray)river["channel"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
            if (ch.Count > 3 && (ch[0] - ch[ch.Count - 1]).sqrMagnitude < 1e-6f) ch.RemoveAt(ch.Count - 1);
            var tri = EarClip(ch);
            var wv = ch.Select(c => new Vector3(c.x, water, c.y)).ToArray();
            for (int k = 0; k < tri.Length; k += 3)
                if (Vector3.Cross(wv[tri[k + 1]] - wv[tri[k]], wv[tri[k + 2]] - wv[tri[k]]).y < 0) (tri[k + 1], tri[k + 2]) = (tri[k + 2], tri[k + 1]);
            MeshObject("River_Water", rv, wv, ch.Select(c => c / 4f).ToArray(), tri, EnvKit.Mat("ENV_Water_Port"), collider: false);
            var centre = ((JArray)river["pts"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
            int wallPieces = 0;
            foreach (JArray bank in (JArray)river["banks"])
            {
                var pts = bank.Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
                for (int i = 0; i + 1 < pts.Count; i++)
                {
                    var a = pts[i];
                    var b = pts[i + 1];
                    float len = Vector2.Distance(new Vector2(a.x, a.z), new Vector2(b.x, b.z));
                    if (len < 0.3f) continue;
                    int n = Mathf.Max(1, Mathf.RoundToInt(len / 4f));
                    var d = new Vector2(b.x - a.x, b.z - a.z) / len;
                    var mid = new Vector2((a.x + b.x) / 2, (a.z + b.z) / 2);
                    var toWater = Nearest(centre, mid) - mid;
                    var nrm = new Vector2(-d.y, d.x);
                    if (Vector2.Dot(nrm, toWater) < 0) nrm = -nrm;
                    float yaw = Mathf.Atan2(nrm.x, nrm.y) * Mathf.Rad2Deg;  // piece +z faces the water
                    for (int k = 0; k < n; k++)
                    {
                        float t = (k + 0.5f) / n;
                        var at = Vector3.Lerp(a, b, t);
                        var go = EnvKit.Place("ENV_Quay_Wall_4m", rv, new Vector3(at.x, at.y, at.z), yaw, new Vector3(len / n / 4f + 0.02f, (at.y - water + 0.6f) / 3.2f, 1));
                        wallPieces++;
                    }
                }
            }
            foreach (JArray p in (JArray)river["parapets"])
            {
                var a = new Vector2((float)p[0][0], (float)p[0][1]);
                var b = new Vector2((float)p[1][0], (float)p[1][1]);
                var d = b - a;
                var mid = (a + b) / 2;
                EnvKit.Place("ENV_Parapet_Rail_2m", rv, new Vector3(mid.x, (float)p[2], mid.y), Mathf.Atan2(d.y, d.x) * -Mathf.Rad2Deg, new Vector3(d.magnitude / 2f, 1, 1));
            }
            foreach (JObject br in (JArray)spec["bridges"]) Bridge(rv, br, water);
            // stone arches under the decks, spanning the channel at each crossing
            foreach (JObject a in (JArray)spec["bridgeArches"] ?? new JArray())
            {
                var mid = new Vector3((float)a["mid"][0], (float)a["y"], (float)a["mid"][1]);
                float yaw = Mathf.Atan2(-(float)a["dir"][1], (float)a["dir"][0]) * Mathf.Rad2Deg;
                EnvKit.Place("ENV_Bridge_Arch", EnvKit.Group(rv, (string)a["id"]), mid, yaw, new Vector3(((float)a["span"] + 0.6f) / 10f, 1f, (float)a["width"]));
            }
            foreach (JObject r in (JArray)spec["riverStairs"] ?? new JArray())
            {
                var at = new Vector3((float)r["at"][0], (float)r["y"], (float)r["at"][1]);
                EnvKit.Place("ENV_River_Stairs", rv, at, Mathf.Atan2(-(float)r["u"][1], (float)r["u"][0]) * Mathf.Rad2Deg);
            }
            var dress = EnvKit.Group(root, "Dressing");
            foreach (JObject f in (JArray)spec["fountains"] ?? new JArray())
                EnvKit.Place("ENV_Fountain_Trough", dress, new Vector3((float)f["at"][0], (float)f["y"], (float)f["at"][1]),
                             Mathf.Atan2((float)f["face"][0], (float)f["face"][1]) * Mathf.Rad2Deg);
            foreach (JObject gi in (JArray)spec["garden"] ?? new JArray())
            {
                bool tree = (string)gi["item"] == "tree";
                // fruit trees, and low solid shrubs (the kit bush reads as red cards at a distance)
                EnvKit.Place(tree ? "ENV_Tree_Plaza" : "ENV_Hill_Tree", dress, new Vector3((float)gi["at"][0], (float)gi["y"], (float)gi["at"][1]), (float)gi["rot"],
                             Vector3.one * (tree ? (float)gi["scale"] : 0.28f * (float)gi["scale"]));
            }
            Backdrop(root, water);
            var st = EnvKit.Group(root, "Stairs");
            foreach (JObject s in (JArray)spec["stairs"]) Stairs(st, s);
            Physics.SyncTransforms();
            var pl = EnvKit.Group(root, "Plazas");
            int seed = 1;
            foreach (JObject pz in (JArray)spec["plazas"])
                DressPlaza(pl, pz, seed++);

            // player at the river plaza
            var plaza = ((JArray)spec["plazas"]).Cast<JObject>().FirstOrDefault(pz => (string)pz["id"] == "Plaza_Rio");
            var spawn = new Vector3(100, 1, 100);
            if (plaza != null)
            {
                var poly = ((JArray)plaza["poly"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
                var c0 = poly.Aggregate(Vector2.zero, (acc, q) => acc + q) / poly.Count;
                spawn = new Vector3(c0.x, ((float?)plaza["y"] ?? 0f) + 0.2f, c0.y);
            }
            // route probe (disabled; enable for a Play Mode walk): the authored tour of the district
            if (spec["route"] is JArray route && route.Count > 1)
            {
                var probe = new GameObject("RouteProbe");
                probe.transform.SetParent(root, false);
                probe.SetActive(false);
                probe.AddComponent<JuegoDef.Dev.JDRouteProbe>().waypoints = route.Select(w => new Vector3((float)w[0], (float)w[2], (float)w[1])).ToArray();
                spawn = new Vector3((float)route[0][0], (float)route[0][2] + 0.2f, (float)route[0][1]);  // arriving from the east along the spine
            }
            EnvStreet.BringPlayer(new JObject { ["_spawnWorld"] = new JArray(spawn.x, spawn.y, spawn.z) });
            EnvKit.EnsureFolder("Assets/JuegoDef/Scenes/ENV");
            var scenePath = $"Assets/JuegoDef/Scenes/ENV/{id}.unity";
            EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(), scenePath);
            int objects = root.GetComponentsInChildren<Transform>(true).Length;
            return $"JD_DISTRICT_FINISH {id} -> {scenePath} objects={objects} riverWalls={wallPieces}";
        }

        /// <summary>Valley backdrop so the casco is not an island in a void: wooded hills rising around the town, a
        /// lower valley opening to the north where the river runs down to the port, and the sea beyond it (owner:
        /// "al fondo se empieza a intuir el mar"). Cheap: one ring mesh, scattered low-cost trees, one sea plane.</summary>
        static void Backdrop(Transform root, float water)
        {
            var g = EnvKit.Group(root, "Backdrop");
            var d = (JArray)spec["district"];
            var c = new Vector2(((float)d[0][0] + (float)d[1][0]) / 2f, ((float)d[0][1] + (float)d[1][1]) / 2f);
            float x0 = (float)d[0][0], z0 = (float)d[0][1], x1 = (float)d[1][0], z1 = (float)d[1][1];
            float r0 = 0.5f * Mathf.Min(x1 - x0, z1 - z0), r1 = 700f;
            // distance outside the district rectangle: the valley floor meets the district edge, hills rise beyond it
            float Out(float x, float z) => new Vector2(Mathf.Max(0, Mathf.Max(x0 - 14f - x, x - x1 - 14f)), Mathf.Max(0, Mathf.Max(z0 - 14f - z, z - z1 - 14f))).magnitude;
            int na = 96, nr = 14;
            var verts = new List<Vector3>();
            var uvs = new List<Vector2>();
            float H(float ang, float r, float dout)
            {
                // north (+z) is the valley towards the port: low; elsewhere wooded hills 40-90 m
                float fromNorth = Mathf.Abs(Mathf.DeltaAngle(ang * Mathf.Rad2Deg, 90f)) / 180f;          // 0 north .. 1 south
                float hill = 40f + 28f * Mathf.Sin(ang * 3f + 0.7f) + 16f * Mathf.Sin(ang * 7f + 2.1f) + 8f * Mathf.Sin(ang * 13f);
                float open = Mathf.Lerp(0.08f, 1f, Mathf.SmoothStep(0.05f, 0.45f, fromNorth));
                if (dout <= 0.01f) return -1.2f;                        // under the district's own ground
                float rise = Mathf.SmoothStep(0f, 1f, (dout - 8f) / 220f);
                return Mathf.Lerp(-0.3f, hill * open, rise) + (fromNorth < 0.12f ? -Mathf.SmoothStep(0f, 1f, (dout - 60f) / 200f) * 7f : 0f);
            }
            for (int j = 0; j <= nr; j++)
            {
                float r = Mathf.Lerp(r0, r1, Mathf.Pow(j / (float)nr, 1.6f));
                for (int i = 0; i < na; i++)
                {
                    float a = 2 * Mathf.PI * i / na;
                    float px = c.x + Mathf.Cos(a) * r, pz = c.y + Mathf.Sin(a) * r;
                    var p = new Vector3(px, H(a, r, Out(px, pz)), pz);
                    verts.Add(p);
                    uvs.Add(new Vector2(p.x, p.z) / 6f);
                }
            }
            var tris = new List<int>();
            for (int j = 0; j < nr; j++)
                for (int i = 0; i < na; i++)
                {
                    int a0 = j * na + i, a1 = j * na + (i + 1) % na, b0 = a0 + na, b1 = a1 + na;
                    tris.AddRange(new[] { a0, b1, a1, a0, b0, b1 });
                }
            var t = tris.ToArray();
            var v = verts.ToArray();
            for (int k = 0; k < t.Length; k += 3)
                if (Vector3.Cross(v[t[k + 1]] - v[t[k]], v[t[k + 2]] - v[t[k]]).y < 0) (t[k + 1], t[k + 2]) = (t[k + 2], t[k + 1]);
            MeshObject("Backdrop_Hills", g, v, uvs.ToArray(), t, EnvKit.Mat("ENV_Ground_Grass"), collider: false);
            // woods on the slopes
            var rng = new System.Random(19);
            for (int k = 0; k < 420; k++)
            {
                float a = (float)(rng.NextDouble() * 2 * Mathf.PI);
                float r = Mathf.Lerp(r0 + 70f, 520f, (float)rng.NextDouble());
                float tx = c.x + Mathf.Cos(a) * r, tz = c.y + Mathf.Sin(a) * r;
                float h = H(a, r, Out(tx, tz));
                if (h < 4f) continue;
                EnvKit.Place("ENV_Hill_Tree", g, new Vector3(c.x + Mathf.Cos(a) * r, h - 0.3f, c.y + Mathf.Sin(a) * r), rng.Next(360), Vector3.one * (1.6f + 1.6f * (float)rng.NextDouble()));
            }
            // the sea to the north, below the town
            var sea = new[] { new Vector3(c.x - 1600, water - 3.5f, c.y + 330), new Vector3(c.x + 1600, water - 3.5f, c.y + 330), new Vector3(c.x + 1600, water - 3.5f, c.y + 2600), new Vector3(c.x - 1600, water - 3.5f, c.y + 2600) };
            MeshObject("Backdrop_Sea", g, sea, sea.Select(p => new Vector2(p.x, p.z) / 20f).ToArray(), new[] { 0, 2, 1, 0, 3, 2 }, EnvKit.Mat("ENV_Water_Port"), collider: false);
        }

        /// <summary>Ground height under (x, z) from the district colliders (ground meshes, decks, stairs).</summary>
        static float GroundY(float x, float z, float fallback)
        {
            var hits = Physics.RaycastAll(new Vector3(x, 80, z), Vector3.down, 200);
            var ground = hits.Where(h => h.collider is MeshCollider && h.collider.name.StartsWith("Ground_") || h.collider.name.Contains("_Deck") || h.collider.name.Contains("_Treads"))
                             .OrderBy(h => h.distance).ToList();
            return ground.Count > 0 ? ground[0].point.y : fallback;
        }

        static bool Inside(List<Vector2> poly, Vector2 p)
        {
            bool c = false;
            for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++)
                if ((poly[i].y > p.y) != (poly[j].y > p.y) && p.x < (poly[j].x - poly[i].x) * (p.y - poly[i].y) / (poly[j].y - poly[i].y) + poly[i].x) c = !c;
            return c;
        }

        static float EdgeDistance(List<Vector2> poly, Vector2 p)
        {
            float best = float.MaxValue;
            for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++)
            {
                var a = poly[j]; var ab = poly[i] - a;
                float t = Mathf.Clamp01(Vector2.Dot(p - a, ab) / Mathf.Max(ab.sqrMagnitude, 1e-6f));
                best = Mathf.Min(best, (a + ab * t - p).magnitude);
            }
            return best;
        }

        /// <summary>Plaza life: trees in iron pits spaced through the open floor, benches facing the centre, lamps
        /// towards the corners; the river plaza gets a bar terrace. Placement stays clear of the plaza edges (street
        /// lanes and facades) and never on the bridge decks.</summary>
        static void DressPlaza(Transform parent, JObject pz, int seed)
        {
            var poly = ((JArray)pz["poly"]).Select(c => new Vector2((float)c[0], (float)c[1])).ToList();
            var g = EnvKit.Group(parent, (string)pz["id"]);
            var rng = new System.Random(seed * 31 + 7);
            float xmin = poly.Min(p => p.x), xmax = poly.Max(p => p.x), zmin = poly.Min(p => p.y), zmax = poly.Max(p => p.y);
            var c0 = poly.Aggregate(Vector2.zero, (a, q) => a + q) / poly.Count;
            float area = 0;
            for (int i = 0, j = poly.Count - 1; i < poly.Count; j = i++) area += (poly[j].x + poly[i].x) * (poly[j].y - poly[i].y);
            area = Mathf.Abs(area) / 2f;
            int trees = Mathf.Clamp(Mathf.RoundToInt(area / 140f), 1, 7);
            var lanes = ((JArray)spec["streets"]).Cast<JObject>()
                .Select(st => (w: (float)st["width"], pts: ((JArray)st["pts"]).Select(q => new Vector2((float)q[0], (float)q[1])).ToList())).ToList();
            bool OnLane(Vector2 p) => lanes.Any(l => (Nearest(l.pts, p) - p).magnitude < l.w / 2f + 1.3f);
            var cands = new List<Vector2>();
            for (float x = xmin; x <= xmax; x += 1.5f)
                for (float z = zmin; z <= zmax; z += 1.5f)
                {
                    var p = new Vector2(x, z);
                    if (Inside(poly, p) && EdgeDistance(poly, p) > 3.2f && !OnLane(p) && Physics.OverlapSphere(new Vector3(x, GroundY(x, z, 0) + 1.5f, z), 1.1f).Length == 0) cands.Add(p);
                }
            var chosen = new List<Vector2>();
            string[] kinds = { "ENV_Tree_Plaza", "ENV_Tree_Plaza", "ENV_Tree_Plaza" };  // solid painted crowns, no alpha cards
            foreach (var p in cands.OrderBy(_ => rng.Next()))
            {
                if (chosen.Count >= trees) break;
                if (chosen.Any(q => (q - p).magnitude < 6.5f)) continue;
                chosen.Add(p);
                float y = GroundY(p.x, p.y, 0);
                EnvKit.Place("ENV_Tree_Pit", g, new Vector3(p.x, y + 0.02f, p.y), 0);
                EnvKit.Place(kinds[chosen.Count % 3], g, new Vector3(p.x, y, p.y), rng.Next(360), Vector3.one * (0.8f + 0.2f * (float)rng.NextDouble()));
                var toC = (c0 - p).normalized;
                var b = p + toC * 1.5f;
                if (!OnLane(b))
                    EnvKit.Place("ENV_Bench_Street", g, new Vector3(b.x, GroundY(b.x, b.y, y), b.y), Mathf.Atan2(toC.x, toC.y) * Mathf.Rad2Deg + 180f);
            }
            // lamps near the three sharpest corners
            foreach (var v in poly.OrderBy(v => EdgeDistance(poly, v + (c0 - v).normalized * 2f)).Take(Mathf.Min(3, poly.Count)))
            {
                var p = v + (c0 - v).normalized * 2.2f;
                if (!Inside(poly, p)) continue;
                EnvKit.Place("ENV_Lamp_Post", g, new Vector3(p.x, GroundY(p.x, p.y, 0), p.y), 0);
            }
            if ((string)pz["id"] == "Plaza_Rio" && cands.Count > 0)
            {
                // kiosk where a 5 m disc stays clear of lanes and trees, nearest the plaza centre
                var kc = cands.Where(p => EdgeDistance(poly, p) > 6f && !lanes.Any(l => (Nearest(l.pts, p) - p).magnitude < l.w / 2f + 5f) && chosen.All(q => (q - p).magnitude > 6f))
                              .OrderBy(p => (p - c0).sqrMagnitude).ToList();
                if (kc.Count > 0)
                {
                    var k = kc[0];
                    EnvKit.Place("ENV_Kiosk_Plaza", g, new Vector3(k.x, GroundY(k.x, k.y, 0), k.y), 22.5f);
                    cands = cands.Where(p => (p - k).magnitude > 5.5f).ToList();
                }
                if (cands.Count == 0) return;
                var t = cands.OrderBy(p => (p - c0).sqrMagnitude).First();
                float y = GroundY(t.x, t.y, 0);
                for (int k = 0; k < 3; k++)
                {
                    var q = new Vector3(t.x + 2.2f * k, y, t.y + (k % 2) * 1.2f);
                    // bar terrace in the owner's photo manner: barrels as tables, stools, a parasol
                    EnvKit.Place("ENV_Parasol", g, q, 0);
                    EnvKit.Place(k % 2 == 0 ? "ENV_Prop_Barrel" : "ENV_Cafe_Table", g, q, rng.Next(360));
                    EnvKit.Place("ENV_Prop_Stool", g, q + new Vector3(0, 0, -0.7f), rng.Next(360));
                    EnvKit.Place("ENV_Prop_Stool", g, q + new Vector3(0.7f, 0, 0.1f), rng.Next(360));
                }
            }
        }

        /// <summary>Point at fraction t (0..1) along a street centreline of the spec, at street level (x, y, z).</summary>
        public static Vector3 StreetPoint(string streetId, float t)
        {
            if (spec == null) spec = JObject.Parse(EnvKit.ReadText($"{DistrictSpecs}/{id ?? "ENV01_Casco_District"}.json"));
            var s = ((JArray)spec["streets"]).Cast<JObject>().First(x => (string)x["id"] == streetId);
            var pts = ((JArray)s["pts"]).Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
            float total = 0;
            for (int i = 0; i + 1 < pts.Count; i++) total += Vector3.Distance(pts[i], pts[i + 1]);
            float want = Mathf.Clamp01(t) * total;
            for (int i = 0; i + 1 < pts.Count; i++)
            {
                float l = Vector3.Distance(pts[i], pts[i + 1]);
                if (want <= l || i == pts.Count - 2) return Vector3.Lerp(pts[i], pts[i + 1], l > 0 ? Mathf.Clamp01(want / l) : 0);
                want -= l;
            }
            return pts[0];
        }

        /// <summary>Eye-level capture along a street: eye at fraction <paramref name="from"/> (1.7 m up, optionally
        /// shifted sideways), looking at fraction <paramref name="to"/> of the same or another street.</summary>
        public static string CaptureStreet(string file, string street, float from, string lookStreet, float to, float side = 0f, float fov = 60f)
        {
            var eye = StreetPoint(street, from);
            var look = StreetPoint(lookStreet ?? street, to);
            var d = look - eye;
            d.y = 0;
            var s = new Vector3(-d.z, 0, d.x).normalized * side;
            return EnvPreview.Capture(file, eye + s + Vector3.up * 1.7f, look + Vector3.up * 2.0f, fov);
        }

        static Vector2 Nearest(List<Vector2> line, Vector2 p)
        {
            var best = line[0];
            float bd = float.MaxValue;
            for (int i = 0; i + 1 < line.Count; i++)
            {
                var a = line[i];
                var ab = line[i + 1] - a;
                float t = Mathf.Clamp01(Vector2.Dot(p - a, ab) / Mathf.Max(ab.sqrMagnitude, 1e-6f));
                var q = a + ab * t;
                float d = (q - p).sqrMagnitude;
                if (d < bd) { bd = d; best = q; }
            }
            return best;
        }

        /// <summary>Stone bridge: a deck slab with setts on top at the bank levels, masonry sides and a stone parapet
        /// each side; the span over the channel reads as a low arch (a stepped soffit). Deck follows the street line.</summary>
        static void Bridge(Transform parent, JObject br, float water)
        {
            var pts = ((JArray)br["pts"]).Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
            float w = (float)br["width"];
            bool foot = (string)br["role"] == "footbridge";
            var g = EnvKit.Group(parent, (string)br["id"]);
            var a = pts[0];
            var b = pts[pts.Count - 1];
            var d = new Vector3(b.x - a.x, 0, b.z - a.z);
            float len = d.magnitude;
            d /= len;
            var side = new Vector3(-d.z, 0, d.x);
            // deck: top quad (setts) + sides and soffit (stone), thickness grows towards the banks (arch read)
            float thick = 0.3f;  // the stone arch module (ENV_Bridge_Arch) carries the body; this is the paved deck
            var verts = new List<Vector3>();
            var tris = new List<int>();
            var uvs = new List<Vector2>();
            void Quad(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 outDir)
            {
                int i0 = verts.Count;
                verts.AddRange(new[] { p0, p1, p2, p3 });
                uvs.AddRange(new[] { new Vector2(p0.x + p0.y, p0.z) / 2f, new Vector2(p1.x + p1.y, p1.z) / 2f, new Vector2(p2.x + p2.y, p2.z) / 2f, new Vector2(p3.x + p3.y, p3.z) / 2f });
                bool flip = Vector3.Dot(Vector3.Cross(p1 - p0, p2 - p0), outDir) < 0;
                tris.AddRange(flip ? new[] { i0, i0 + 2, i0 + 1, i0, i0 + 3, i0 + 2 } : new[] { i0, i0 + 1, i0 + 2, i0, i0 + 2, i0 + 3 });
            }
            int n = 12;
            var top = new List<(Vector3 l, Vector3 r, float soffit)>();
            for (int k = 0; k <= n; k++)
            {
                float t = k / (float)n;
                var c = Vector3.Lerp(a, b, t) + Vector3.up * 0.02f;
                float arch = thick;
                top.Add((c + side * w / 2, c - side * w / 2, arch));
            }
            var deckV = new List<Vector3>();
            for (int k = 0; k < n; k++)
            {
                var (l0, r0, s0) = top[k];
                var (l1, r1, s1) = top[k + 1];
                Quad(l0, l1, r1, r0, Vector3.up);                                                                      // deck top
                Quad(l0 - Vector3.up * s0, l1 - Vector3.up * s1, l1, l0, side);                                         // left side
                Quad(r0, r1, r1 - Vector3.up * s1, r0 - Vector3.up * s0, -side);                                        // right side
                Quad(r0 - Vector3.up * s0, r1 - Vector3.up * s1, l1 - Vector3.up * s1, l0 - Vector3.up * s0, Vector3.down); // soffit
            }
            var vs = verts.ToArray();
            var ts = tris.ToArray();
            MeshObject((string)br["id"] + "_Deck", g, vs, uvs.ToArray(), ts, EnvKit.Mat("ENV_Ground_Setts_Warm"), collider: true);
            // parapets: kit rubble retaining wall pieces, 0.95 m high, both sides
            int np = Mathf.Max(1, Mathf.RoundToInt(len / 2f));
            float yaw = Mathf.Atan2(-d.z, d.x) * Mathf.Rad2Deg;
            for (int k = 0; k < np; k++)
            {
                var c = Vector3.Lerp(a, b, (k + 0.5f) / np);
                foreach (var sgn in new[] { 1f, -1f })
                {
                    var at = c + side * sgn * (w / 2f - 0.2f) + Vector3.up * 0.95f;
                    EnvKit.Place("ENV_Retaining_Wall_2x2", g, at, yaw + (sgn > 0 ? 0 : 180), new Vector3(len / np / 2f, 0.5f, 0.45f));
                }
            }
        }

        /// <summary>Stepped lane (escalinata): long treads with low risers between the two street levels, stone
        /// nosings, a skirt down the open sides. One mesh per stair (treads: flags; risers: rock trim).</summary>
        static void Stairs(Transform parent, JObject s)
        {
            var pts = ((JArray)s["pts"]).Select(c => new Vector3((float)c[0], (float)c[2], (float)c[1])).ToList();
            float w = (float)s["width"];
            var a = pts[0];
            var b = pts[pts.Count - 1];
            if (a.y > b.y) (a, b) = (b, a);
            float rise = b.y - a.y;
            var d = new Vector3(b.x - a.x, 0, b.z - a.z);
            float len = d.magnitude;
            d /= len;
            var side = new Vector3(-d.z, 0, d.x) * (w / 2f + 0.3f);
            int steps = Mathf.Max(2, Mathf.CeilToInt(rise / 0.16f));
            float tread = len / steps, riser = rise / steps;
            var tv = new List<Vector3>(); var tt = new List<int>(); var tu = new List<Vector2>();
            var rv = new List<Vector3>(); var rt = new List<int>(); var ru = new List<Vector2>();
            void Quad(List<Vector3> V, List<int> T, List<Vector2> U, Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 outDir)
            {
                int i0 = V.Count;
                bool vertical = Mathf.Abs(outDir.y) < 0.5f;
                V.AddRange(new[] { p0, p1, p2, p3 });
                var across = Vector3.Cross(Vector3.up, outDir).normalized;
                foreach (var p in new[] { p0, p1, p2, p3 }) U.Add(vertical ? new Vector2(Vector3.Dot(p, across), p.y) / 2f : new Vector2(p.x, p.z) / 2f);
                bool flip = Vector3.Dot(Vector3.Cross(p1 - p0, p2 - p0), outDir) < 0;
                T.AddRange(flip ? new[] { i0, i0 + 2, i0 + 1, i0, i0 + 3, i0 + 2 } : new[] { i0, i0 + 1, i0 + 2, i0, i0 + 2, i0 + 3 });
            }
            for (int k = 0; k < steps; k++)
            {
                var c0 = a + d * (tread * k);
                var c1 = a + d * (tread * (k + 1));
                float y = a.y + riser * (k + 1);
                var l0 = new Vector3(c0.x, y, c0.z) + side; var r0 = new Vector3(c0.x, y, c0.z) - side;
                var l1 = new Vector3(c1.x, y, c1.z) + side; var r1 = new Vector3(c1.x, y, c1.z) - side;
                Quad(tv, tt, tu, l0, l1, r1, r0, Vector3.up);                                            // tread
                var lb = l0 - Vector3.up * riser; var rb = r0 - Vector3.up * riser;
                Quad(rv, rt, ru, lb, l0, r0, rb, -d);                                                    // riser (faces down-slope)
                float skirt = y - a.y + 0.4f;
                Quad(rv, rt, ru, l1 - Vector3.up * skirt, l1, l0, l0 - Vector3.up * skirt, side);        // open side left
                Quad(rv, rt, ru, r0 - Vector3.up * skirt, r0, r1, r1 - Vector3.up * skirt, -side);       // open side right
            }
            var g = EnvKit.Group(parent, (string)s["id"]);
            MeshObject((string)s["id"] + "_Treads", g, tv.ToArray(), tu.ToArray(), tt.ToArray(), EnvKit.Mat("ENV_Ground_Flag_Light"), collider: true);
            MeshObject((string)s["id"] + "_Risers", g, rv.ToArray(), ru.ToArray(), rt.ToArray(), EnvKit.Mat("MI_RockTrim"), collider: true);
        }

        /// <summary>Ear clipping for a simple polygon (the river channel), returns triangle indices.</summary>
        static int[] EarClip(List<Vector2> poly)
        {
            var idx = Enumerable.Range(0, poly.Count).ToList();
            float area = 0;
            for (int i = 0; i < poly.Count; i++) area += poly[i].x * poly[(i + 1) % poly.Count].y - poly[(i + 1) % poly.Count].x * poly[i].y;
            if (area < 0) idx.Reverse();
            var tris = new List<int>();
            int guard = 0;
            while (idx.Count > 3 && guard++ < 10000)
            {
                bool clipped = false;
                for (int i = 0; i < idx.Count; i++)
                {
                    int i0 = idx[(i + idx.Count - 1) % idx.Count], i1 = idx[i], i2 = idx[(i + 1) % idx.Count];
                    var a = poly[i0]; var b = poly[i1]; var c = poly[i2];
                    if ((b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x) <= 0) continue;  // reflex
                    bool inside = false;
                    foreach (var j in idx)
                    {
                        if (j == i0 || j == i1 || j == i2) continue;
                        if (InTri(poly[j], a, b, c)) { inside = true; break; }
                    }
                    if (inside) continue;
                    tris.AddRange(new[] { i0, i1, i2 });
                    idx.RemoveAt(i);
                    clipped = true;
                    break;
                }
                if (!clipped) break;
            }
            if (idx.Count == 3) tris.AddRange(idx);
            return tris.ToArray();
        }

        static bool InTri(Vector2 p, Vector2 a, Vector2 b, Vector2 c)
        {
            float d1 = (p.x - b.x) * (a.y - b.y) - (a.x - b.x) * (p.y - b.y);
            float d2 = (p.x - c.x) * (b.y - c.y) - (b.x - c.x) * (p.y - c.y);
            float d3 = (p.x - a.x) * (c.y - a.y) - (c.x - a.x) * (p.y - a.y);
            bool neg = d1 < 0 || d2 < 0 || d3 < 0, pos = d1 > 0 || d2 > 0 || d3 > 0;
            return !(neg && pos);
        }
    }
}
